// Gallery data for Takazudo Modular Panels
// Contains 260 images with slugs, blurhash values, and metadata

export const galleryData = [
  {
    slug: "panels-gallery-zudo-blocks-141",
    imageAlt: "",
    blurhash: "UFFNxM^d=D~9:kJ.o~EMnAnTIWNf%L=Z-6b^",
    user: "Takazudo",
    description: "Built this beauty over the weekend",
    created_at: "2025-08-22T19:05:23.711Z",
    hashtags: ["#synthlife", "#DIY", "#geartalk", "#gearpost", "#musicgear"],
  },
  {
    slug: "panels-gallery-zudo-blocks-142",
    imageAlt: "",
    blurhash: "UXHJs+ae^3$%niS#xFfi}AbHW;o0%1R*n%oe",
    user: "Alice",
    description: "Built this beauty over the weekend",
    created_at: "2025-03-21T23:11:45.259Z",
    hashtags: [
      "#studioporn",
      "#handmade",
      "#musicproduction",
      "#DIYcase",
      "#modular",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-103",
    imageAlt: "",
    blurhash: "UhK*MBRn}=$%o2xFxFj@t6jtWVj[oLj[oeay",
    user: "Takazudo",
    description: "Another successful DIY project",
    created_at: "2024-05-05T22:12:58.953Z",
    hashtags: [
      "#homestudio",
      "#handmade",
      "#analogsynth",
      "#eurorack",
      "#modular",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-104",
    imageAlt: "",
    blurhash: "UYKkcaOD}p$PrtWDs.jZ^Ms.NIj?jbS4s,sA",
    user: "Takazudo",
    description: "DIY modular synth case done",
    created_at: "2024-08-30T05:45:41.068Z",
    hashtags: [
      "#woodworking",
      "#electronicmusic",
      "#modularsynthesizer",
      "#customcase",
      "#geartalk",
      "#DIYcase",
      "#synthesizer",
      "#DIYproject",
      "#synth",
      "#DIY",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-105",
    imageAlt: "",
    blurhash: "UTKt}5W:}pNdi}WDxYWV}po1I=ocsBWWoeay",
    user: "Alice",
    description: "The perfect size for my needs",
    created_at: "2025-11-01T17:55:39.331Z",
    hashtags: [
      "#modular",
      "#woodworking",
      "#handmade",
      "#synthlife",
      "#studioporn",
      "#DIYaudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-106",
    imageAlt: "",
    blurhash: "ULE-p-Ip]%S$9vbHs.R+|=s.W=n$kqR*s9W=",
    user: "Takazudo",
    description: "This setup is pure joy",
    created_at: "2024-08-25T14:25:39.093Z",
    hashtags: [
      "#woodworking",
      "#eurorack",
      "#handmade",
      "#musicproduction",
      "#synthcase",
      "#customcase",
      "#synthesizer",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-107",
    imageAlt: "",
    blurhash: "URGj$:E1=Zoz57X8s:R*|=xZkCn$XmRjw^bI",
    user: "Bob",
    description: "This case sounds incredible",
    created_at: "2024-01-18T12:32:13.985Z",
    hashtags: [
      "#modularsynth",
      "#modularsynthesizer",
      "#handmade",
      "#gearpost",
      "#DIY",
      "#musicgear",
      "#studiosetup",
      "#DIYaudio",
      "#geartalk",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-108",
    imageAlt: "",
    blurhash: "UHJ;@}E2^$M}D+WCs:WB~7oI#:xENLNH$$R,",
    user: "Alice",
    description: "My synth corner is looking good",
    created_at: "2025-10-23T13:54:19.253Z",
    hashtags: ["#maker", "#woodworking", "#modularsynthesizer"],
  },
  {
    slug: "panels-gallery-zudo-blocks-109",
    imageAlt: "",
    blurhash: "UEO]9v0KYz#X9FNb-Be-C{$*;QxsxdM{xrkD",
    user: "Takazudo",
    description: "My modular case is finally complete",
    created_at: "2024-01-12T19:10:11.621Z",
    hashtags: ["#rackcase", "#synthcase", "#studioporn", "#modular"],
  },
  {
    slug: "panels-gallery-zudo-blocks-110",
    imageAlt: "",
    blurhash: "UPF4ikEN}qNdaeoLn+jZ$hs-oeoJESWCxCS4",
    user: "Bob",
    description: "The perfect size for my needs",
    created_at: "2025-02-18T23:29:07.068Z",
    hashtags: [
      "#gearpost",
      "#modularsynthesizer",
      "#synthesizer",
      "#patchcables",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-111",
    imageAlt: "",
    blurhash: "UdJ$sMM|,?ofSbj[n+ay}ns.R,oJERWBxEa}",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-03-23T04:39:00.431Z",
    hashtags: [
      "#musicgear",
      "#DIY",
      "#eurorack",
      "#DIYaudio",
      "#musicproduction",
      "#geartalk",
      "#synth",
      "#patchcables",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-112",
    imageAlt: "",
    blurhash: "UMICvWvz=Y%210Rknjof}7kqbvV@R7ShODr?",
    user: "Alice",
    description: "DIY eurorack at its finest",
    created_at: "2024-09-22T14:42:05.876Z",
    hashtags: [
      "#modularsynthesizer",
      "#synthesizer",
      "#DIYproject",
      "#patchcables",
      "#studiosetup",
      "#modular",
      "#customcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-113",
    imageAlt: "",
    blurhash: "UKJYFbjE?FbuAENHNINw}=SgENwc#Ts.J7$g",
    user: "Bob",
    description: "Sweet new case for the studio",
    created_at: "2025-09-17T08:11:21.369Z",
    hashtags: [
      "#electronicmusic",
      "#geartalk",
      "#DIYproject",
      "#patchcables",
      "#musicproduction",
      "#modular",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-114",
    imageAlt: "",
    blurhash: "UELdDUm-^~V]D+nis.R+~St4i{s,v%NHt6R+",
    user: "Takazudo",
    description: "This build exceeded my expectations",
    created_at: "2025-03-23T22:34:40.476Z",
    hashtags: [
      "#geartalk",
      "#modular",
      "#gearpost",
      "#musicproduction",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-115",
    imageAlt: "",
    blurhash: "UOM#FR={.4$%21ofWDt7hdt7M}ShX.bIj?WC",
    user: "Takazudo",
    description: "Perfect fit for my modules",
    created_at: "2024-05-25T17:13:05.784Z",
    hashtags: [
      "#synthcase",
      "#patchcables",
      "#electronicmusic",
      "#synthesizer",
      "#modular",
      "#customcase",
      "#studiosetup",
      "#analogsynth",
      "#musicproduction",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-116",
    imageAlt: "",
    blurhash: "UKH]g+=_xt%1CRWXs:of_LSgV[WW=yoeRjay",
    user: "Takazudo",
    description: "Time to patch some cables",
    created_at: "2024-09-17T06:56:23.994Z",
    hashtags: ["#modularsynth", "#gearpost", "#musicproduction"],
  },
  {
    slug: "panels-gallery-zudo-blocks-117",
    imageAlt: "",
    blurhash: "UbM;jw-oxt$%7N%2R-NH?]ozf7oLx]kCxFoJ",
    user: "Alice",
    description: "My synth corner is looking good",
    created_at: "2024-03-13T18:42:52.419Z",
    hashtags: [
      "#patchcables",
      "#homestudio",
      "#modularsynthesizer",
      "#gearpost",
      "#modular",
      "#DIYaudio",
      "#DIYcase",
      "#analogsynth",
      "#modularsynth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-118",
    imageAlt: "",
    blurhash: "UaKR%u=|o}S#Lzt7t6n%.7NajFNb=|Rkaewf",
    user: "Alice",
    description: "Time to patch some cables",
    created_at: "2024-03-15T08:22:08.491Z",
    hashtags: [
      "#DIYproject",
      "#modularsynth",
      "#synth",
      "#musicgear",
      "#gearpost",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-119",
    imageAlt: "",
    blurhash: "UCLm;axZ?@=x05R,14N_uMNaozOrKiJQ.5oz",
    user: "Takazudo",
    description: "Been working on this for months",
    created_at: "2024-01-30T05:11:08.659Z",
    hashtags: ["#DIY", "#synthcase", "#synth", "#modular", "#patchcables"],
  },
  {
    slug: "panels-gallery-zudo-blocks-120",
    imageAlt: "",
    blurhash: "UiJQJ{xu$zxZC8%LNdR+~Bt7tQt6bbjaxaoL",
    user: "Takazudo",
    description: "So happy with this build",
    created_at: "2025-10-27T12:27:33.135Z",
    hashtags: [
      "#modularsynth",
      "#rackcase",
      "#synthesizer",
      "#customcase",
      "#homestudio",
      "#studioporn",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-121",
    imageAlt: "",
    blurhash: "UoL:AZxD$gxZGukCRkR*~VbbSNWVt7ofxZs:",
    user: "Bob",
    description: "My modular case is finally complete",
    created_at: "2025-04-16T03:44:56.142Z",
    hashtags: ["#DIY", "#synthesizer", "#modularsynth", "#patchcables"],
  },
  {
    slug: "panels-gallery-zudo-blocks-122",
    imageAlt: "",
    blurhash: "UuL:4LxasmxaC8ofWBkC~Bt7R*j@s:ofoJWB",
    user: "Alice",
    description: "My synth corner is looking good",
    created_at: "2024-10-07T16:52:44.704Z",
    hashtags: [
      "#eurorack",
      "#eurorack",
      "#analogsynth",
      "#gearpost",
      "#musicgear",
      "#maker",
      "#rackcase",
      "#DIY",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-123",
    imageAlt: "",
    blurhash: "UuMivJWU%1xtGcoLWXbb~Vs:R*oL%MW=sSjZ",
    user: "Alice",
    description: "Ready to make some noise",
    created_at: "2024-03-05T09:04:19.956Z",
    hashtags: ["#DIYaudio", "#synthlife", "#synth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-124",
    imageAlt: "",
    blurhash: "UXIgil}q^NxaK+J.JAni~UozbbI=-;slWBxG",
    user: "Alice",
    description: "Custom panel design worked perfectly",
    created_at: "2024-11-25T15:24:45.280Z",
    hashtags: [
      "#synthcase",
      "#eurorack",
      "#customcase",
      "#synthlife",
      "#DIYproject",
      "#studiosetup",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-125",
    imageAlt: "",
    blurhash: "UTF~N,NdxGtQ~VkCxZt6_3%1R*oL%g$%I:oe",
    user: "Alice",
    description: "Been working on this for months",
    created_at: "2025-01-22T09:27:47.743Z",
    hashtags: ["#DIYcase", "#modularsynth", "#woodworking", "#eurorack"],
  },
  {
    slug: "panels-gallery-zudo-blocks-126",
    imageAlt: "",
    blurhash: "UaHB3n-Ut7oz}qwIRQxa^4%1f5jF=aV@ozWB",
    user: "Takazudo",
    description: "Been working on this for months",
    created_at: "2025-04-28T12:45:53.587Z",
    hashtags: ["#synthlife", "#handmade", "#patchcables", "#DIYaudio"],
  },
  {
    slug: "panels-gallery-zudo-blocks-127",
    imageAlt: "",
    blurhash: "UUI|ah^4^N$$5=xaxawv}?s:S$NHX.I;W;Nx",
    user: "Bob",
    description: "DIY modular synth case done",
    created_at: "2024-10-05T20:59:57.275Z",
    hashtags: ["#synthesizer", "#DIYcase", "#maker"],
  },
  {
    slug: "panels-gallery-zudo-blocks-128",
    imageAlt: "",
    blurhash: "URLeHA?F%e$%1*S6Nxxa?[xboMJUY5%1%0oM",
    user: "Alice",
    description: "Love the finish on this one",
    created_at: "2025-03-23T23:59:17.327Z",
    hashtags: ["#musicgear", "#DIY", "#modularsynth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-129",
    imageAlt: "",
    blurhash: "UfLeWrxY$%s:GuafR+of_Lt6bHW;%Mbuj?of",
    user: "Bob",
    description: "Proud of this one",
    created_at: "2024-05-03T05:00:15.501Z",
    hashtags: [
      "#eurorack",
      "#musicgear",
      "#synth",
      "#analogsynth",
      "#DIYproject",
      "#rackcase",
      "#woodworking",
      "#homestudio",
      "#DIYaudio",
      "#DIY",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-130",
    imageAlt: "",
    blurhash: "UdM}s?%Lx@-VGbkWNbkC_MsCRjS2O?xFw]fk",
    user: "Bob",
    description: "My workspace is complete",
    created_at: "2025-01-28T11:03:47.625Z",
    hashtags: [
      "#homestudio",
      "#geartalk",
      "#DIY",
      "#synthlife",
      "#maker",
      "#customcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-131",
    imageAlt: "",
    blurhash: "UbM}R5tlO=xuK+xuSgXS?]s.rsn*7eaKwIr?",
    user: "Takazudo",
    description: "Finally got my rack layout perfect",
    created_at: "2025-10-11T22:48:29.732Z",
    hashtags: [
      "#modular",
      "#gearpost",
      "#analogsynth",
      "#electronicmusic",
      "#DIYaudio",
      "#studiosetup",
      "#maker",
      "#musicproduction",
      "#synthlife",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-132",
    imageAlt: "",
    blurhash: "UGLdx^T0?Z--0;~BWZENqD%Mo#$$krTJx@ix",
    user: "Bob",
    description: "Proud of this one",
    created_at: "2025-02-09T06:37:37.574Z",
    hashtags: ["#DIYaudio", "#DIYcase", "#patchcables"],
  },
  {
    slug: "panels-gallery-zudo-blocks-133",
    imageAlt: "",
    blurhash: "UNJFS}yBr={|Ly^PKNFv.RJR;4X8-;E*Eg#:",
    user: "Alice",
    description: "Been working on this for months",
    created_at: "2024-01-03T11:13:04.874Z",
    hashtags: [
      "#studiosetup",
      "#modular",
      "#electronicmusic",
      "#modularsynthesizer",
      "#patchcables",
      "#maker",
      "#synthcase",
      "#eurorack",
      "#studioporn",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-134",
    imageAlt: "",
    blurhash: "UJKG{s-.Bj,DG@}Y-9OXY4tQv~$4-o%1NaR+",
    user: "Bob",
    description: "Finally got my rack layout perfect",
    created_at: "2024-12-04T23:10:08.580Z",
    hashtags: [
      "#modularsynth",
      "#DIYaudio",
      "#synthlife",
      "#synth",
      "#customcase",
      "#analogsynth",
      "#gearpost",
      "#homestudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-135",
    imageAlt: "",
    blurhash: "UOL,n9x[F@-B%xkW}FoyyV$jOqFv^PFxNu+_",
    user: "Bob",
    description: "Custom panel design worked perfectly",
    created_at: "2025-08-09T17:45:49.637Z",
    hashtags: [
      "#synthcase",
      "#homestudio",
      "#synth",
      "#DIYproject",
      "#analogsynth",
      "#modular",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-136",
    imageAlt: "",
    blurhash: "UKJZYYxd^P%J2xJ:I[$%~D?FtOEQx^=_$$S4",
    user: "Takazudo",
    description: "My modular case is finally complete",
    created_at: "2025-01-20T02:11:17.361Z",
    hashtags: ["#synthcase", "#eurorack", "#gearpost", "#DIYcase"],
  },
  {
    slug: "panels-gallery-zudo-blocks-137",
    imageAlt: "",
    blurhash: "UJIW}bES07~89SI@^yni=}^zM}Ib~UV|WE%H",
    user: "Alice",
    description: "Another successful DIY project",
    created_at: "2025-09-14T04:26:22.584Z",
    hashtags: [
      "#electronicmusic",
      "#gearpost",
      "#synth",
      "#customcase",
      "#handmade",
      "#studiosetup",
      "#DIY",
      "#woodworking",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-138",
    imageAlt: "",
    blurhash: "UIIMoxBk=xwM14};kWAFIcwNxt^MXB5Wwfr=",
    user: "Bob",
    description: "Another successful DIY project",
    created_at: "2025-01-21T12:00:29.684Z",
    hashtags: ["#synthesizer", "#DIY", "#gearpost", "#DIYcase"],
  },
  {
    slug: "panels-gallery-zudo-blocks-139",
    imageAlt: "",
    blurhash: "UTIDEk?a^Pt5B=KjbcxG~Cx[W;I=%f$%n$s+",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-04-04T14:54:13.738Z",
    hashtags: [
      "#modular",
      "#handmade",
      "#DIYcase",
      "#DIY",
      "#analogsynth",
      "#eurorack",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-140",
    imageAlt: "",
    blurhash: "UkJZPIxsxXxDBpxsX7bH~BofWqofo~RnoLbH",
    user: "Takazudo",
    description: "Clean cable management achieved",
    created_at: "2024-05-19T11:52:04.432Z",
    hashtags: ["#handmade", "#studioporn", "#modularsynth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-085",
    imageAlt: "",
    blurhash: "UNIW=zxZp_xu.8bIxGi_*IjFn4S2^+ozNan+",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-09-27T16:50:31.278Z",
    hashtags: ["#synth", "#synthcase", "#rackcase", "#maker"],
  },
  {
    slug: "panels-gallery-zudo-blocks-086",
    imageAlt: "",
    blurhash: "UPIzxLs9E#%M~pwKV[pHPUa~m,n$-opHoym-",
    user: "Takazudo",
    description: "Been working on this for months",
    created_at: "2025-05-30T08:53:00.510Z",
    hashtags: [
      "#modularsynth",
      "#customcase",
      "#DIYcase",
      "#synthlife",
      "#maker",
      "#homestudio",
      "#synthcase",
      "#musicproduction",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-087",
    imageAlt: "",
    blurhash: "UYMre.^j%e%1Vq$$bHae?@-UR7NbI:nir]Sg",
    user: "Bob",
    description: "DIY eurorack at its finest",
    created_at: "2025-03-14T04:19:54.088Z",
    hashtags: [
      "#geartalk",
      "#DIYcase",
      "#musicproduction",
      "#rackcase",
      "#studiosetup",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-088",
    imageAlt: "",
    blurhash: "UVMq-K_0-.$%0{NHS1t6?[S1I;M|=tb]kCW;",
    user: "Bob",
    description: "Time to patch some cables",
    created_at: "2025-10-04T22:14:19.991Z",
    hashtags: ["#patchcables", "#studiosetup", "#eurorack"],
  },
  {
    slug: "panels-gallery-zudo-blocks-089",
    imageAlt: "",
    blurhash: "UUMFdq=x%zx[01a$I;RlY$OER7n,AWWV$*of",
    user: "Bob",
    description: "Been working on this for months",
    created_at: "2024-11-06T00:57:19.525Z",
    hashtags: [
      "#gearpost",
      "#synthlife",
      "#homestudio",
      "#DIYproject",
      "#electronicmusic",
      "#DIY",
      "#synthcase",
      "#musicproduction",
      "#geartalk",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-090-2",
    imageAlt: "",
    blurhash: "UrC=NMAh,NJC#;Nuo#WGn$oHW,jskEajnnbD",
    user: "Takazudo",
    description: "Custom panel design worked perfectly",
    created_at: "2024-07-16T23:42:53.333Z",
    hashtags: ["#modularsynth", "#rackcase", "#woodworking", "#geartalk"],
  },
  {
    slug: "panels-gallery-zudo-blocks-091-2",
    imageAlt: "",
    blurhash: "UF9@-BCi[FYE_bM$-Pzz,EnTr=$e-|O*#-br",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-07-06T16:53:14.625Z",
    hashtags: [
      "#modular",
      "#patchcables",
      "#musicgear",
      "#maker",
      "#geartalk",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-092-2",
    imageAlt: "",
    blurhash: "UgH1rN~V^*%M9~t8xvxu$yWBRjWBoJxYslRj",
    user: "Bob",
    description: "Love the finish on this one",
    created_at: "2024-05-16T23:40:55.195Z",
    hashtags: [
      "#homestudio",
      "#DIYaudio",
      "#rackcase",
      "#gearpost",
      "#musicgear",
      "#electronicmusic",
      "#DIYcase",
      "#analogsynth",
      "#synthesizer",
      "#synth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-093-2",
    imageAlt: "",
    blurhash: "UlDcXO~q_2-;t6ofWBR*n$jXV@RPaxaxayay",
    user: "Takazudo",
    description: "Working on my dream setup",
    created_at: "2024-08-09T19:44:44.539Z",
    hashtags: [
      "#modularsynth",
      "#electronicmusic",
      "#DIYaudio",
      "#DIY",
      "#maker",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-094",
    imageAlt: "",
    blurhash: "UWNIW$^Qy;tk0LRo9vs.HAJBrFjIF@WW-BWo",
    user: "Takazudo",
    description: "Ready to make some noise",
    created_at: "2025-11-09T16:39:01.327Z",
    hashtags: [
      "#eurorack",
      "#DIYaudio",
      "#geartalk",
      "#synthesizer",
      "#analogsynth",
      "#synthlife",
      "#eurorack",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-095",
    imageAlt: "",
    blurhash: "UpM$uHxax]xHI-X9NJV_?[bHM}flX4nixGoe",
    user: "Bob",
    description: "My modular journey continues",
    created_at: "2025-04-04T22:30:23.035Z",
    hashtags: [
      "#DIYcase",
      "#geartalk",
      "#modularsynthesizer",
      "#analogsynth",
      "#DIY",
      "#gearpost",
      "#DIYproject",
      "#modular",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-096",
    imageAlt: "",
    blurhash: "UqN+nM%1t+s;EKW?NKai.kW=R7WXo_sAxGoe",
    user: "Alice",
    description: "Love the finish on this one",
    created_at: "2025-05-23T00:35:17.791Z",
    hashtags: [
      "#electronicmusic",
      "#woodworking",
      "#DIYaudio",
      "#modularsynth",
      "#synthcase",
      "#customcase",
      "#studiosetup",
      "#studioporn",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-097",
    imageAlt: "",
    blurhash: "UUM6O@=_~n$*0dWFM|ofy:R-IWNet3s.X9WC",
    user: "Takazudo",
    description: "My synth corner is looking good",
    created_at: "2024-08-10T06:45:39.375Z",
    hashtags: ["#modularsynthesizer", "#rackcase", "#gearpost", "#synthcase"],
  },
  {
    slug: "panels-gallery-zudo-blocks-098",
    imageAlt: "",
    blurhash: "UWLfEg=_.6$g0eWCaLoy*GbbMzR,M{M|NeV[",
    user: "Bob",
    description: "Sweet new case for the studio",
    created_at: "2024-02-27T23:29:13.296Z",
    hashtags: [
      "#handmade",
      "#modularsynth",
      "#eurorack",
      "#studiosetup",
      "#rackcase",
      "#musicgear",
      "#synthesizer",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-099",
    imageAlt: "",
    blurhash: "UXKAG|-o?axa0xRlM|R-?[j]IpW=R6tQkCo0",
    user: "Takazudo",
    description: "Finally got my rack layout perfect",
    created_at: "2025-01-19T10:25:13.462Z",
    hashtags: [
      "#synthesizer",
      "#electronicmusic",
      "#modularsynthesizer",
      "#musicproduction",
      "#studiosetup",
      "#synth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-100",
    imageAlt: "",
    blurhash: "UcIN1@M$F2of.iR:#qs:?Es:NeWqbvkUaga#",
    user: "Bob",
    description: "Sweet new case for the studio",
    created_at: "2024-06-14T13:49:15.204Z",
    hashtags: ["#DIY", "#rackcase", "#geartalk", "#synth", "#handmade"],
  },
  {
    slug: "zudo-rail-nuts-in-life1",
    imageAlt: "",
    blurhash: "UGDvJ-%MkCxu00Rj%2M{9FD%t8of-;s:-pRj",
    user: "Alice",
    description: "Love how this turned out",
    created_at: "2024-10-27T11:34:45.039Z",
    hashtags: ["#woodworking", "#handmade", "#rackcase"],
  },
  {
    slug: "zudo-rail-nuts-in-life2",
    imageAlt: "",
    blurhash: "UDD+|Y~V-;D%00kCM{xuxFoft8Rj-;x]jZRj",
    user: "Takazudo",
    description: "My modular case is finally complete",
    created_at: "2025-07-30T08:49:52.999Z",
    hashtags: [
      "#musicgear",
      "#handmade",
      "#DIYaudio",
      "#DIY",
      "#studioporn",
      "#geartalk",
      "#gearpost",
      "#maker",
      "#modularsynthesizer",
      "#synthcase",
    ],
  },
  {
    slug: "zudo-rail-nuts-in-life3",
    imageAlt: "",
    blurhash: "U9D0J200-;_4.8~q_3xut7t7xuM|~qM{xuD%",
    user: "Bob",
    description: "My synth corner is looking good",
    created_at: "2024-11-03T18:33:02.713Z",
    hashtags: ["#woodworking", "#DIYcase", "#eurorack"],
  },
  {
    slug: "zudo-rail-nuts-in-life4",
    imageAlt: "",
    blurhash: "U7A0-d00xu?I~qayIUD%RkRjxuxu-;t7RjD%",
    user: "Takazudo",
    description: "Custom case for my modules",
    created_at: "2025-03-30T12:45:27.394Z",
    hashtags: ["#woodworking", "#DIYcase", "#customcase", "#musicgear"],
  },
  {
    slug: "zudo-rail-nuts-in-life5",
    imageAlt: "",
    blurhash: "UBC?xBxu00~q%MRjRj%L%Mt7D%%MxuRj9FRj",
    user: "Bob",
    description: "Love how this turned out",
    created_at: "2024-08-28T23:54:25.771Z",
    hashtags: [
      "#synthlife",
      "#geartalk",
      "#DIYaudio",
      "#gearpost",
      "#woodworking",
      "#maker",
      "#modular",
      "#DIY",
      "#DIYproject",
    ],
  },
  {
    slug: "zudo-rail-nuts-in-life6",
    imageAlt: "",
    blurhash: "UFDcT{-;~q%M%MRjRjM{M{M{xuM{~qWBRjRj",
    user: "Bob",
    description: "This build exceeded my expectations",
    created_at: "2025-04-22T21:14:19.288Z",
    hashtags: ["#DIYproject", "#handmade", "#gearpost", "#modularsynthesizer"],
  },
  {
    slug: "zudo-rail-nuts-in-life7",
    imageAlt: "",
    blurhash: "UDD+|Y~V-;D%00kCM{xuxFoft8Rj-;x]jZRj",
    user: "Bob",
    description: "DIY eurorack at its finest",
    created_at: "2025-10-02T23:34:52.285Z",
    hashtags: [
      "#customcase",
      "#eurorack",
      "#studioporn",
      "#rackcase",
      "#geartalk",
      "#patchcables",
      "#gearpost",
    ],
  },
  {
    slug: "zudo-rail-overview1",
    imageAlt: "",
    blurhash: "U7C?^W_4~q-;-;xuxuWB-;ofRjM{~qWBWBM{",
    user: "Bob",
    description: "Working on my dream setup",
    created_at: "2024-06-02T12:54:20.131Z",
    hashtags: [
      "#DIY",
      "#analogsynth",
      "#electronicmusic",
      "#maker",
      "#synthcase",
      "#DIYcase",
      "#studioporn",
      "#modularsynthesizer",
      "#patchcables",
      "#modularsynth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-001",
    imageAlt: "",
    blurhash: "UFFEQFIpY5ELuOJm#,%2Tx}[R5bv^kE1K5wI",
    user: "Alice",
    description: "Sweet new case for the studio",
    created_at: "2025-01-04T05:42:41.151Z",
    hashtags: [
      "#synthlife",
      "#synthesizer",
      "#analogsynth",
      "#synthcase",
      "#woodworking",
      "#electronicmusic",
      "#studioporn",
      "#synth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-002",
    imageAlt: "",
    blurhash: "UNJt6c%0~po#O=.7xFRS_2-VoyXR-CaOxtxW",
    user: "Bob",
    description: "Love the finish on this one",
    created_at: "2024-01-31T04:45:52.715Z",
    hashtags: [
      "#rackcase",
      "#handmade",
      "#synthcase",
      "#studiosetup",
      "#DIYproject",
      "#customcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-003",
    imageAlt: "",
    blurhash: "USIDmq_L^+%fI.oHv$Nb-;t8-otPVztS%K%1",
    user: "Takazudo",
    description: "Great project to work on",
    created_at: "2025-03-12T06:01:31.275Z",
    hashtags: [
      "#handmade",
      "#studiosetup",
      "#modularsynthesizer",
      "#maker",
      "#homestudio",
      "#analogsynth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-004",
    imageAlt: "",
    blurhash: "URHU^04ot5W=?vD%IUoz~Wj?Rjt7?ZxtRjR*",
    user: "Alice",
    description: "Just finished this amazing build!",
    created_at: "2025-01-14T17:50:58.479Z",
    hashtags: ["#eurorack", "#geartalk", "#musicgear", "#DIYproject"],
  },
  {
    slug: "panels-gallery-zudo-blocks-005",
    imageAlt: "",
    blurhash: "UpFFNn%0%2t6~Vsls:oJ-oRjR+WqxZR*NHWB",
    user: "Bob",
    description: "Custom case for my modules",
    created_at: "2024-09-19T02:23:04.803Z",
    hashtags: [
      "#geartalk",
      "#eurorack",
      "#modularsynth",
      "#customcase",
      "#DIY",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-006",
    imageAlt: "",
    blurhash: "UMGuUPVD^*V@?w,-WVS6~VnMR*S%?bV@E1M}",
    user: "Alice",
    description: "My workspace is complete",
    created_at: "2025-02-20T13:23:48.448Z",
    hashtags: ["#modularsynth", "#customcase", "#musicproduction"],
  },
  {
    slug: "panels-gallery-zudo-blocks-007",
    imageAlt: "",
    blurhash: "USG[N5WX$LV@^ij?RPt7~ANHozofr=IpxaNI",
    user: "Takazudo",
    description: "This setup is pure joy",
    created_at: "2024-01-01T09:41:31.072Z",
    hashtags: ["#analogsynth", "#modular", "#DIYcase", "#geartalk"],
  },
  {
    slug: "panels-gallery-zudo-blocks-008",
    imageAlt: "",
    blurhash: "USH-x%n#}QxuXTIpi^s9}QWYJCnh$w$%tSX9",
    user: "Takazudo",
    description: "Clean cable management achieved",
    created_at: "2025-06-29T12:31:17.372Z",
    hashtags: [
      "#eurorack",
      "#electronicmusic",
      "#studioporn",
      "#woodworking",
      "#DIYproject",
      "#musicproduction",
      "#DIY",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-009",
    imageAlt: "",
    blurhash: "UKJZbt#n?@KNwHnhNxNI?@Nxixrr%eIp$jxa",
    user: "Takazudo",
    description: "My synth corner is looking good",
    created_at: "2024-07-22T18:40:05.929Z",
    hashtags: [
      "#gearpost",
      "#electronicmusic",
      "#synthcase",
      "#DIYaudio",
      "#woodworking",
      "#DIY",
      "#patchcables",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-010",
    imageAlt: "",
    blurhash: "UHKuN4]$KK=w3FwbWBWEuhWBv$S4Po0~#mX7",
    user: "Alice",
    description: "Hand-crafted with love",
    created_at: "2024-01-20T01:24:20.912Z",
    hashtags: [
      "#musicgear",
      "#eurorack",
      "#maker",
      "#handmade",
      "#DIYaudio",
      "#modularsynthesizer",
      "#musicproduction",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-011",
    imageAlt: "",
    blurhash: "URI43G#lL1Ki.mR*#Swd%~X8n4xG?bkCRkbb",
    user: "Takazudo",
    description: "My modular journey continues",
    created_at: "2024-10-06T06:39:54.752Z",
    hashtags: [
      "#modularsynth",
      "#woodworking",
      "#eurorack",
      "#homestudio",
      "#electronicmusic",
      "#eurorack",
      "#analogsynth",
      "#DIYcase",
      "#DIYproject",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-012",
    imageAlt: "",
    blurhash: "UaHT8C}q^1=F=wWBNcX8,.$iS4WW]ioySgWC",
    user: "Bob",
    description: "Love the finish on this one",
    created_at: "2024-01-27T13:31:01.814Z",
    hashtags: [
      "#eurorack",
      "#homestudio",
      "#geartalk",
      "#analogsynth",
      "#electronicmusic",
      "#woodworking",
      "#modularsynth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-013",
    imageAlt: "",
    blurhash: "UQG@b=}?;M=HB:t79_JB^iOrI;R+TJW;s:kV",
    user: "Alice",
    description: "My modular journey continues",
    created_at: "2024-11-24T01:07:11.574Z",
    hashtags: [
      "#homestudio",
      "#DIYproject",
      "#maker",
      "#analogsynth",
      "#synth",
      "#synthlife",
      "#musicgear",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-014",
    imageAlt: "",
    blurhash: "UUJtFz$e}:xF_M-6M_Iq~VRPE1fk%gE2M{t7",
    user: "Bob",
    description: "My modular case is finally complete",
    created_at: "2024-11-06T19:47:13.065Z",
    hashtags: [
      "#handmade",
      "#DIYcase",
      "#customcase",
      "#DIYproject",
      "#maker",
      "#geartalk",
      "#musicgear",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-015",
    imageAlt: "",
    blurhash: "UTGI7R4:-nE1~q-AMxoe~Bn$IUxa-.RPafoe",
    user: "Takazudo",
    description: "Proud of this one",
    created_at: "2024-01-22T13:37:35.884Z",
    hashtags: ["#analogsynth", "#musicgear", "#studioporn"],
  },
  {
    slug: "panels-gallery-zudo-blocks-016",
    imageAlt: "",
    blurhash: "UcHeB.#ir;of_NMxRjog?cR%nMs,?askIVR-",
    user: "Bob",
    description: "Love the finish on this one",
    created_at: "2025-02-20T02:52:16.730Z",
    hashtags: [
      "#modularsynth",
      "#DIYproject",
      "#maker",
      "#eurorack",
      "#musicgear",
      "#DIYaudio",
      "#analogsynth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-017",
    imageAlt: "",
    blurhash: "UXIqMo$Kn4Rk~pRP9aNHkYIpM{xst8WBj;oe",
    user: "Bob",
    description: "This case sounds incredible",
    created_at: "2024-08-04T02:04:26.813Z",
    hashtags: [
      "#musicproduction",
      "#studioporn",
      "#synthesizer",
      "#maker",
      "#eurorack",
      "#patchcables",
      "#modularsynth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-018",
    imageAlt: "",
    blurhash: "UPHBeq0m9G~3I_-O-nItt8nh-nN1?aV[V?jY",
    user: "Bob",
    description: "DIY eurorack at its finest",
    created_at: "2024-09-06T14:59:57.687Z",
    hashtags: ["#modularsynthesizer", "#studioporn", "#geartalk"],
  },
  {
    slug: "panels-gallery-zudo-blocks-019",
    imageAlt: "",
    blurhash: "UWI;V9$0rpxv?wIUD%xu^+WBIUWWt7s:NGRj",
    user: "Takazudo",
    description: "Love how this turned out",
    created_at: "2025-11-07T05:05:25.630Z",
    hashtags: [
      "#patchcables",
      "#modularsynthesizer",
      "#synth",
      "#rackcase",
      "#eurorack",
      "#studiosetup",
      "#DIYproject",
      "#eurorack",
      "#geartalk",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-020",
    imageAlt: "",
    blurhash: "UUHCJ@vx~p%MK6s:NJbv~ps.S$x^yDayjEkC",
    user: "Takazudo",
    description: "Great project to work on",
    created_at: "2024-09-01T21:06:17.917Z",
    hashtags: [
      "#musicproduction",
      "#DIYaudio",
      "#homestudio",
      "#synthlife",
      "#gearpost",
      "#synthcase",
      "#rackcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-021",
    imageAlt: "",
    blurhash: "UWH.ZwrB_2%gO@tRNHg4~ps.Nex^xtWBtSoJ",
    user: "Alice",
    description: "Great project to work on",
    created_at: "2025-07-04T09:07:33.643Z",
    hashtags: ["#DIY", "#maker", "#customcase", "#gearpost", "#handmade"],
  },
  {
    slug: "panels-gallery-zudo-blocks-022",
    imageAlt: "",
    blurhash: "URJk4P8_~q_2pK-:%hI[oH-=JAogxubvkC%2",
    user: "Bob",
    description: "Hand-crafted with love",
    created_at: "2025-03-06T03:36:11.473Z",
    hashtags: [
      "#analogsynth",
      "#musicgear",
      "#studioporn",
      "#studiosetup",
      "#homestudio",
      "#woodworking",
      "#modular",
      "#synth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-023",
    imageAlt: "",
    blurhash: "UNKm%+8wnMpJ.TI9IUtSxuM{kCt7%LM{kDIp",
    user: "Bob",
    description: "My workspace is complete",
    created_at: "2024-05-13T01:14:20.402Z",
    hashtags: [
      "#geartalk",
      "#eurorack",
      "#studioporn",
      "#analogsynth",
      "#studiosetup",
      "#musicgear",
      "#woodworking",
      "#rackcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-024",
    imageAlt: "",
    blurhash: "UQIN?c9F}=-;yZaJWAtS~AozS5xuxBt7oet7",
    user: "Alice",
    description: "Great project to work on",
    created_at: "2024-09-20T02:01:32.209Z",
    hashtags: [
      "#studiosetup",
      "#gearpost",
      "#rackcase",
      "#synthesizer",
      "#synthcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-025",
    imageAlt: "",
    blurhash: "UQEoY=IAn3%M%gn$R*of~VRjM{%2Rjju%2Ri",
    user: "Alice",
    description: "DIY eurorack at its finest",
    created_at: "2024-11-29T00:35:23.558Z",
    hashtags: [
      "#synth",
      "#modular",
      "#handmade",
      "#analogsynth",
      "#synthesizer",
      "#synthlife",
      "#modularsynthesizer",
      "#gearpost",
      "#electronicmusic",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-026",
    imageAlt: "",
    blurhash: "UQDcEs^*9G9G~p?HM_IBR;og$y$yt8o2xC%0",
    user: "Alice",
    description: "Love the finish on this one",
    created_at: "2025-06-09T08:06:46.753Z",
    hashtags: [
      "#woodworking",
      "#geartalk",
      "#musicproduction",
      "#eurorack",
      "#rackcase",
      "#modularsynth",
      "#DIYproject",
      "#DIY",
      "#studiosetup",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-027",
    imageAlt: "",
    blurhash: "UOF~N.R3~BS6yZivM_x]_4i]ROtRksIUi^kX",
    user: "Takazudo",
    description: "My workspace is complete",
    created_at: "2025-10-10T01:27:19.951Z",
    hashtags: ["#studioporn", "#electronicmusic", "#woodworking", "#synth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-028",
    imageAlt: "",
    blurhash: "USJj*h?c%gxv-.IUxCxY~oM|Mxt4?GxuNxWC",
    user: "Takazudo",
    description: "Perfect fit for my modules",
    created_at: "2024-06-16T05:34:50.480Z",
    hashtags: [
      "#musicgear",
      "#woodworking",
      "#geartalk",
      "#modularsynthesizer",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-029",
    imageAlt: "",
    blurhash: "UKI|:k=u~p%L1%E1M|xsyDD,4px[nQv~RRJm",
    user: "Takazudo",
    description: "Proud of this one",
    created_at: "2024-05-07T01:51:39.533Z",
    hashtags: [
      "#handmade",
      "#electronicmusic",
      "#modularsynth",
      "#DIYproject",
      "#gearpost",
      "#studioporn",
      "#rackcase",
      "#eurorack",
      "#geartalk",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-030",
    imageAlt: "",
    blurhash: "UlHdy]?Hads9_NtlRjWU?HXSRPWBXSI=RQsn",
    user: "Takazudo",
    description: "This setup is pure joy",
    created_at: "2024-09-11T23:14:06.330Z",
    hashtags: [
      "#DIYcase",
      "#synth",
      "#synthcase",
      "#synthesizer",
      "#DIYproject",
      "#musicgear",
      "#modular",
      "#rackcase",
      "#woodworking",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-031",
    imageAlt: "",
    blurhash: "UkFO}wkX%MoM~pt8s:bI-:WBV@axslWCNGoK",
    user: "Bob",
    description: "This build exceeded my expectations",
    created_at: "2024-08-02T23:10:30.971Z",
    hashtags: [
      "#customcase",
      "#maker",
      "#musicproduction",
      "#eurorack",
      "#rackcase",
      "#studiosetup",
      "#modularsynthesizer",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-032",
    imageAlt: "",
    blurhash: "UIFh{+xY%=OBNdS2EOjc.aovrKr]pCt6r?t2",
    user: "Takazudo",
    description: "Perfect fit for my modules",
    created_at: "2024-03-30T12:49:47.677Z",
    hashtags: [
      "#synthcase",
      "#synth",
      "#modularsynthesizer",
      "#DIYcase",
      "#geartalk",
      "#gearpost",
      "#handmade",
      "#synthesizer",
      "#rackcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-033",
    imageAlt: "",
    blurhash: "UDF=Zn^JuUGWy6WExrkBuUtPz|;g%LxXRQow",
    user: "Takazudo",
    description: "This setup is pure joy",
    created_at: "2025-03-04T22:06:11.700Z",
    hashtags: [
      "#homestudio",
      "#geartalk",
      "#patchcables",
      "#DIYproject",
      "#DIY",
      "#rackcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-034",
    imageAlt: "",
    blurhash: "UKH1z@S^GQ-U-CSdNsj0*7$#voW:7V$j=fOT",
    user: "Bob",
    description: "Love how this turned out",
    created_at: "2024-08-30T00:29:04.492Z",
    hashtags: [
      "#modularsynth",
      "#woodworking",
      "#customcase",
      "#synthlife",
      "#DIYaudio",
      "#eurorack",
      "#eurorack",
      "#handmade",
      "#homestudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-035",
    imageAlt: "",
    blurhash: "UNEfAYvl-4bbyxAHpFkB~3w0VaW-OlI;R:sm",
    user: "Takazudo",
    description: "Time to patch some cables",
    created_at: "2024-11-27T10:27:25.809Z",
    hashtags: ["#musicgear", "#DIYcase", "#modular", "#analogsynth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-036",
    imageAlt: "",
    blurhash: "UCF;}^P8*FxY3x+OXNS$u2OXH[RR[XpFnURj",
    user: "Takazudo",
    description: "This case sounds incredible",
    created_at: "2024-06-06T07:44:57.896Z",
    hashtags: ["#DIYaudio", "#musicproduction", "#DIYcase"],
  },
  {
    slug: "panels-gallery-zudo-blocks-037",
    imageAlt: "",
    blurhash: "UCFq?lP8*Fou3L+gXgogYNODH[Rk{~cBaPR%",
    user: "Takazudo",
    description: "This case sounds incredible",
    created_at: "2025-01-25T23:33:53.651Z",
    hashtags: [
      "#studiosetup",
      "#DIY",
      "#modularsynthesizer",
      "#synthcase",
      "#patchcables",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-038",
    imageAlt: "",
    blurhash: "UmK^f}T0}=WZMfERRmsV^iSiIqVsxvofs*r?",
    user: "Alice",
    description: "Built this beauty over the weekend",
    created_at: "2024-12-26T10:42:56.343Z",
    hashtags: [
      "#homestudio",
      "#gearpost",
      "#eurorack",
      "#studioporn",
      "#patchcables",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-039",
    imageAlt: "",
    blurhash: "UiLMtz9#}[%MRpEQWEs:~Te:I:wbX9n*xYbF",
    user: "Bob",
    description: "This build exceeded my expectations",
    created_at: "2025-01-29T23:55:31.670Z",
    hashtags: [
      "#gearpost",
      "#musicproduction",
      "#modularsynth",
      "#DIYaudio",
      "#customcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-040",
    imageAlt: "",
    blurhash: "UrL3ulJD}=j^XAIti{s:?EsmOEjFRja#t7oc",
    user: "Alice",
    description: "Working on my dream setup",
    created_at: "2024-09-26T14:43:41.868Z",
    hashtags: [
      "#geartalk",
      "#synthlife",
      "#homestudio",
      "#studiosetup",
      "#handmade",
      "#eurorack",
      "#woodworking",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-041",
    imageAlt: "",
    blurhash: "UiLfy?J:^3tQ9hT0nPNd~AR,IqX8i_Rjt6t6",
    user: "Takazudo",
    description: "My synth corner is looking good",
    created_at: "2024-06-29T18:56:17.537Z",
    hashtags: ["#studiosetup", "#modularsynth", "#musicgear"],
  },
  {
    slug: "panels-gallery-zudo-blocks-042",
    imageAlt: "",
    blurhash: "UTJ*6Vr??v-pD4j]MzM{~WoMM{tQMzfP-:$%",
    user: "Takazudo",
    description: "This case sounds incredible",
    created_at: "2024-08-09T22:59:09.233Z",
    hashtags: [
      "#gearpost",
      "#studioporn",
      "#customcase",
      "#rackcase",
      "#modularsynthesizer",
      "#DIYcase",
      "#homestudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-043",
    imageAlt: "",
    blurhash: "UWHUg^?b~U^%%cRUs,bF=?ERs.slS}rsWBR*",
    user: "Bob",
    description: "Proud of this one",
    created_at: "2024-04-27T11:40:44.711Z",
    hashtags: [
      "#geartalk",
      "#electronicmusic",
      "#musicproduction",
      "#DIYaudio",
      "#handmade",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-044",
    imageAlt: "",
    blurhash: "UbIqZA^+~VtR$frWWrRi^*W=f6NHn~NGWWbH",
    user: "Takazudo",
    description: "Custom panel design worked perfectly",
    created_at: "2024-01-11T05:58:02.215Z",
    hashtags: [
      "#synth",
      "#studioporn",
      "#synthesizer",
      "#synthlife",
      "#musicgear",
      "#rackcase",
      "#woodworking",
      "#DIYaudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-045",
    imageAlt: "",
    blurhash: "UdHnvg4o-:nh~AWBoJxa$y%LV@WWsmt6a}M|",
    user: "Alice",
    description: "Clean cable management achieved",
    created_at: "2024-11-15T01:09:05.552Z",
    hashtags: ["#DIYaudio", "#synthlife", "#analogsynth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-046",
    imageAlt: "",
    blurhash: "UbMGIsxZ?vx[+DkqbInO~oXURRtR$xM}T0kr",
    user: "Bob",
    description: "The perfect size for my needs",
    created_at: "2024-10-11T18:19:39.246Z",
    hashtags: ["#geartalk", "#maker", "#modularsynth", "#gearpost"],
  },
  {
    slug: "panels-gallery-zudo-blocks-047",
    imageAlt: "",
    blurhash: "UZJ6$mPBtP,q_K%2$~J7~ANd#Rae=sNHEL$M",
    user: "Takazudo",
    description: "Custom case for my modules",
    created_at: "2024-09-16T00:11:52.626Z",
    hashtags: ["#woodworking", "#modularsynthesizer", "#eurorack"],
  },
  {
    slug: "panels-gallery-zudo-blocks-048",
    imageAlt: "",
    blurhash: "UYLDlOwt?bWA=WDhkXxt~UxYIqaLsj%1RoM{",
    user: "Bob",
    description: "So happy with this build",
    created_at: "2025-11-06T10:36:38.602Z",
    hashtags: ["#eurorack", "#patchcables", "#geartalk", "#handmade"],
  },
  {
    slug: "panels-gallery-zudo-blocks-049",
    imageAlt: "",
    blurhash: "UCI4^W^+?b?a00s:s,Ri~XV?D%WE^*kDNfbH",
    user: "Takazudo",
    description: "The perfect size for my needs",
    created_at: "2024-10-01T16:04:27.173Z",
    hashtags: [
      "#DIYaudio",
      "#maker",
      "#gearpost",
      "#DIYproject",
      "#DIYcase",
      "#woodworking",
      "#eurorack",
      "#musicproduction",
      "#modular",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-050",
    imageAlt: "",
    blurhash: "UeINmlRO~A%2_3nhS#o}^*WVI:xux[oeRjoz",
    user: "Alice",
    description: "DIY modular synth case done",
    created_at: "2024-01-30T15:34:08.885Z",
    hashtags: [
      "#DIY",
      "#analogsynth",
      "#gearpost",
      "#musicgear",
      "#eurorack",
      "#modularsynth",
      "#electronicmusic",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-051",
    imageAlt: "",
    blurhash: "UcJa7WIU^gt7~paJRkg3^%RjR+og%Ln$R*X8",
    user: "Bob",
    description: "Custom case for my modules",
    created_at: "2024-08-15T05:49:48.998Z",
    hashtags: ["#woodworking", "#eurorack", "#DIYaudio", "#gearpost"],
  },
  {
    slug: "panels-gallery-zudo-blocks-052",
    imageAlt: "",
    blurhash: "USGRem#Q=^-pyERjIpxt~UM{xtNG-:n$WBW;",
    user: "Alice",
    description: "My latest eurorack creation",
    created_at: "2025-05-12T12:51:40.859Z",
    hashtags: [
      "#homestudio",
      "#synthlife",
      "#studioporn",
      "#DIYaudio",
      "#musicproduction",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-053",
    imageAlt: "",
    blurhash: "UTJ%n3VX};-:_Mr;ELkX}?WWX9t7axS5tRbF",
    user: "Alice",
    description: "Working on my dream setup",
    created_at: "2025-07-13T07:20:26.642Z",
    hashtags: [
      "#DIYaudio",
      "#handmade",
      "#musicgear",
      "#electronicmusic",
      "#homestudio",
      "#analogsynth",
      "#rackcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-054",
    imageAlt: "",
    blurhash: "UGFPr|y3I%-:~os,WAxoT6xsxdM|tbt7M}a#",
    user: "Alice",
    description: "My workspace is complete",
    created_at: "2024-10-27T14:01:46.137Z",
    hashtags: [
      "#handmade",
      "#DIYcase",
      "#eurorack",
      "#synthesizer",
      "#modularsynth",
      "#musicgear",
      "#synthcase",
      "#studiosetup",
      "#musicproduction",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-055",
    imageAlt: "",
    blurhash: "UGF?RNtKEH%K_KxsW,t6J]xtsHoe%cs-ajj?",
    user: "Takazudo",
    description: "Working on my dream setup",
    created_at: "2024-06-06T12:15:42.505Z",
    hashtags: [
      "#studioporn",
      "#maker",
      "#electronicmusic",
      "#synthesizer",
      "#DIY",
      "#analogsynth",
      "#patchcables",
      "#synthcase",
      "#musicproduction",
      "#synth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-056",
    imageAlt: "",
    blurhash: "UDDTUc%KXct6_ItKV[%K%,tKV|t6.4xcN0Ri",
    user: "Takazudo",
    description: "Time to patch some cables",
    created_at: "2025-03-12T12:25:28.552Z",
    hashtags: ["#eurorack", "#analogsynth", "#maker"],
  },
  {
    slug: "panels-gallery-zudo-blocks-057",
    imageAlt: "",
    blurhash: "U6C77k%ek{oy.Gxroft3GLte%NW-_LxrIDtP",
    user: "Alice",
    description: "This build exceeded my expectations",
    created_at: "2024-06-09T20:41:02.891Z",
    hashtags: ["#synthlife", "#rackcase", "#analogsynth", "#DIYcase"],
  },
  {
    slug: "panels-gallery-zudo-blocks-058",
    imageAlt: "",
    blurhash: "UHFG8J%dS;%r_Kada^n.yJouakt5y2s=bIR$",
    user: "Alice",
    description: "My latest eurorack creation",
    created_at: "2024-05-06T14:06:48.511Z",
    hashtags: [
      "#maker",
      "#modular",
      "#musicproduction",
      "#eurorack",
      "#patchcables",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-059",
    imageAlt: "",
    blurhash: "UBC%o?xtyKbo??xZRStM?#t3aRoy%qtLRkou",
    user: "Takazudo",
    description: "Been working on this for months",
    created_at: "2025-05-09T10:13:50.967Z",
    hashtags: [
      "#electronicmusic",
      "#modular",
      "#handmade",
      "#analogsynth",
      "#gearpost",
      "#modularsynth",
      "#synthlife",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-060",
    imageAlt: "",
    blurhash: "UcM%ZJe-~7x]z-ae$wxv~UoeIVo#-poKSiR.",
    user: "Alice",
    description: "This case sounds incredible",
    created_at: "2025-07-20T20:24:11.905Z",
    hashtags: ["#eurorack", "#DIY", "#geartalk", "#DIYaudio"],
  },
  {
    slug: "panels-gallery-zudo-blocks-061",
    imageAlt: "",
    blurhash: "UbMjEZbE~7x]+XWVwax]~Ut6E3XA-;a{NySi",
    user: "Takazudo",
    description: "Built this beauty over the weekend",
    created_at: "2025-02-07T16:05:30.977Z",
    hashtags: [
      "#eurorack",
      "#rackcase",
      "#geartalk",
      "#musicgear",
      "#synthcase",
      "#synthlife",
      "#eurorack",
      "#analogsynth",
      "#homestudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-062",
    imageAlt: "",
    blurhash: "UlL|ojs+_2xWrUf5ozs+~To#NKkC${X9bwbc",
    user: "Takazudo",
    description: "Ready to make some noise",
    created_at: "2024-10-23T13:12:04.213Z",
    hashtags: [
      "#studiosetup",
      "#modularsynth",
      "#modularsynthesizer",
      "#synthcase",
      "#gearpost",
      "#synth",
      "#electronicmusic",
      "#rackcase",
      "#DIYaudio",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-063",
    imageAlt: "",
    blurhash: "UoMQ30xB%hw[#5V@XToe~UkDI[W=n$t8bIR-",
    user: "Bob",
    description: "Hand-crafted with love",
    created_at: "2025-09-01T01:18:12.512Z",
    hashtags: [
      "#homestudio",
      "#rackcase",
      "#woodworking",
      "#eurorack",
      "#studioporn",
      "#modular",
      "#studiosetup",
      "#geartalk",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-064",
    imageAlt: "",
    blurhash: "UmO3Udv{.9xt;[i]Ngf6~VbHI@W=M_t7t7WB",
    user: "Bob",
    description: "Time to patch some cables",
    created_at: "2024-11-18T12:01:04.778Z",
    hashtags: [
      "#synth",
      "#DIY",
      "#DIYaudio",
      "#synthesizer",
      "#eurorack",
      "#rackcase",
      "#DIYproject",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-065",
    imageAlt: "",
    blurhash: "UrMjBWskx^s,z-aeXUjY~UbINekCaef+oea}",
    user: "Alice",
    description: "Perfect fit for my modules",
    created_at: "2025-08-21T14:07:32.193Z",
    hashtags: [
      "#eurorack",
      "#DIY",
      "#DIYaudio",
      "#geartalk",
      "#modular",
      "#gearpost",
      "#musicproduction",
      "#DIYproject",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-066",
    imageAlt: "",
    blurhash: "UpMso:$dx^s.+rngT1ax~VRkNej[M|R+j?jY",
    user: "Takazudo",
    description: "Love how this turned out",
    created_at: "2025-02-16T18:15:51.499Z",
    hashtags: ["#studiosetup", "#modular", "#maker", "#DIYaudio", "#geartalk"],
  },
  {
    slug: "panels-gallery-zudo-blocks-067",
    imageAlt: "",
    blurhash: "UpM7JexV?bxtn2s*RljY~UoIR.j[?FRjo~kC",
    user: "Takazudo",
    description: "My latest eurorack creation",
    created_at: "2025-08-28T20:20:55.031Z",
    hashtags: [
      "#studiosetup",
      "#rackcase",
      "#eurorack",
      "#musicproduction",
      "#handmade",
      "#woodworking",
      "#DIYcase",
      "#DIYaudio",
      "#patchcables",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-068",
    imageAlt: "",
    blurhash: "UoMZmvr:%hxZ+YnhS%V@~UWBI=ofV@R*t7oJ",
    user: "Bob",
    description: "Ready to make some noise",
    created_at: "2025-10-11T23:25:47.722Z",
    hashtags: [
      "#synthcase",
      "#musicproduction",
      "#modular",
      "#patchcables",
      "#geartalk",
      "#studiosetup",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-069",
    imageAlt: "",
    blurhash: "UqMZgexB%gxV+radbxjF~UX9NKbcR5bcR,bI",
    user: "Bob",
    description: "Hand-crafted with love",
    created_at: "2024-08-26T19:59:29.594Z",
    hashtags: [
      "#DIY",
      "#woodworking",
      "#synth",
      "#modular",
      "#customcase",
      "#eurorack",
      "#gearpost",
      "#synthcase",
      "#DIYaudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-070",
    imageAlt: "",
    blurhash: "UtMj5Dngx^xV+radXTn$~UozNIbIRPozoeWX",
    user: "Alice",
    description: "Just finished this amazing build!",
    created_at: "2025-02-11T23:41:25.706Z",
    hashtags: [
      "#eurorack",
      "#geartalk",
      "#DIYcase",
      "#studioporn",
      "#customcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-071",
    imageAlt: "",
    blurhash: "UpMi}|s8%gxC+radT0jY~UbcNIkDMybIs.ay",
    user: "Bob",
    description: "Proud of this one",
    created_at: "2024-05-11T15:07:44.463Z",
    hashtags: [
      "#DIYcase",
      "#DIYproject",
      "#maker",
      "#woodworking",
      "#handmade",
      "#DIYaudio",
      "#DIY",
      "#analogsynth",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-072",
    imageAlt: "",
    blurhash: "UNHo5m?FM{t8ad~pxuIU~pt6t6j[t7%LofWB",
    user: "Alice",
    description: "This case sounds incredible",
    created_at: "2025-02-18T13:35:35.837Z",
    hashtags: ["#DIY", "#geartalk", "#studioporn", "#synth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-073",
    imageAlt: "",
    blurhash: "UPIzVRR6_0Si?wVtIotR~qsmIUoz-=R*Iot7",
    user: "Bob",
    description: "Been working on this for months",
    created_at: "2025-09-24T10:30:14.419Z",
    hashtags: [
      "#customcase",
      "#eurorack",
      "#woodworking",
      "#musicgear",
      "#homestudio",
      "#patchcables",
      "#DIY",
      "#studiosetup",
      "#rackcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-074",
    imageAlt: "",
    blurhash: "UZKJrxng?]s:PCoIslj[uOslrWa|%4n$RiWY",
    user: "Takazudo",
    description: "This build exceeded my expectations",
    created_at: "2024-09-03T21:05:04.674Z",
    hashtags: [
      "#DIYcase",
      "#modularsynthesizer",
      "#studioporn",
      "#maker",
      "#patchcables",
      "#geartalk",
      "#DIYproject",
      "#eurorack",
      "#DIYaudio",
      "#musicproduction",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-075",
    imageAlt: "",
    blurhash: "URJZ#mS4~Tx]~qxtE2xv%zk9Rjt7S}M|xHs.",
    user: "Bob",
    description: "This setup is pure joy",
    created_at: "2025-05-13T17:57:33.825Z",
    hashtags: ["#musicgear", "#rackcase", "#gearpost"],
  },
  {
    slug: "panels-gallery-zudo-blocks-076",
    imageAlt: "",
    blurhash: "UcKc6LnNS[f,~WV@IUWYYNNG#mofO=RjaebI",
    user: "Bob",
    description: "The perfect size for my needs",
    created_at: "2024-07-02T04:40:06.513Z",
    hashtags: [
      "#synthesizer",
      "#DIYproject",
      "#DIYcase",
      "#maker",
      "#gearpost",
      "#modularsynthesizer",
      "#DIYaudio",
      "#woodworking",
      "#studioporn",
      "#electronicmusic",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-077",
    imageAlt: "",
    blurhash: "UYM#F;i]p]n+~XxCNsog8He-v#S4pdjEZ~WY",
    user: "Takazudo",
    description: "So happy with this build",
    created_at: "2025-04-03T15:09:48.965Z",
    hashtags: [
      "#customcase",
      "#studioporn",
      "#woodworking",
      "#gearpost",
      "#synthlife",
      "#homestudio",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-078",
    imageAlt: "",
    blurhash: "ULLKmZ$|3MtQ=xoeK1j[3xXR{,fhtQj[wyjb",
    user: "Bob",
    description: "Hand-crafted with love",
    created_at: "2024-03-02T22:54:59.062Z",
    hashtags: [
      "#modular",
      "#modularsynth",
      "#modularsynthesizer",
      "#DIY",
      "#synthesizer",
      "#geartalk",
      "#patchcables",
      "#musicgear",
      "#homestudio",
      "#electronicmusic",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-079",
    imageAlt: "",
    blurhash: "UFHm46$~3hpFTWoet5jt3_XO{+t3}st5NIoe",
    user: "Bob",
    description: "Just finished this amazing build!",
    created_at: "2024-11-24T09:31:13.480Z",
    hashtags: [
      "#customcase",
      "#maker",
      "#studiosetup",
      "#gearpost",
      "#synthesizer",
      "#musicgear",
      "#rackcase",
      "#geartalk",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-080",
    imageAlt: "",
    blurhash: "UGHAX;%E3gkl^6:=S}FZ4IsA:=OU%gBiF=wM",
    user: "Takazudo",
    description: "My modular case is finally complete",
    created_at: "2025-01-09T00:04:40.684Z",
    hashtags: [
      "#studioporn",
      "#eurorack",
      "#synth",
      "#geartalk",
      "#gearpost",
      "#modular",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-081",
    imageAlt: "",
    blurhash: "URJh~v$%3NKJ|ybHOpw{3zSe+}soB*soOTJQ",
    user: "Alice",
    description: "Love how this turned out",
    created_at: "2025-01-24T01:32:38.487Z",
    hashtags: [
      "#musicproduction",
      "#patchcables",
      "#modular",
      "#eurorack",
      "#electronicmusic",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-082",
    imageAlt: "",
    blurhash: "UEG@C@TW3y]-?FsAS_TE4Ft3|_FcTtWDs+w0",
    user: "Takazudo",
    description: "My workspace is complete",
    created_at: "2025-04-02T17:34:19.899Z",
    hashtags: ["#DIY", "#synthlife", "#DIYaudio"],
  },
  {
    slug: "panels-gallery-zudo-blocks-083",
    imageAlt: "",
    blurhash: "UAIVl2^J3_GR}X{mX72-3_xG{,N_={AC7F$j",
    user: "Alice",
    description: "So happy with this build",
    created_at: "2025-09-03T18:03:24.128Z",
    hashtags: ["#synthcase", "#DIYaudio", "#synth"],
  },
  {
    slug: "panels-gallery-zudo-blocks-084",
    imageAlt: "",
    blurhash: "UZHnjHD%-;kC~AaLR%bc=_g3Ipag%0X8W;jY",
    user: "Takazudo",
    description: "My synth corner is looking good",
    created_at: "2025-10-21T09:28:26.273Z",
    hashtags: ["#DIYaudio", "#DIYproject", "#handmade"],
  },
  {
    slug: "panel-variations",
    imageAlt: "",
    blurhash: "UVKd3oq]}Z#EMJ#9=f#l_1xBV@wKtjJ5I[RU",
    user: "Alice",
    description: "Love the finish on this one",
    created_at: "2025-02-01T13:01:06.554Z",
    hashtags: [
      "#modularsynthesizer",
      "#eurorack",
      "#gearpost",
      "#maker",
      "#eurorack",
      "#handmade",
      "#musicproduction",
      "#DIYaudio",
      "#DIYcase",
      "#synth",
    ],
  },
  {
    slug: "zb40l-construction",
    imageAlt: "",
    blurhash: "UFHACD9b,.xtv%I@$%AE{{ozAHNa109^xZkC",
    user: "Alice",
    description: "Proud of this one",
    created_at: "2025-05-05T15:47:45.454Z",
    hashtags: [
      "#modularsynth",
      "#woodworking",
      "#musicgear",
      "#studioporn",
      "#synth",
      "#handmade",
      "#rackcase",
      "#synthlife",
      "#analogsynth",
    ],
  },
  {
    slug: "zb40-green-a-1",
    imageAlt: "",
    blurhash: "UWK][LEl5Zt6Gw-QxCoJX.X9$eWW-TjZadR+",
    user: "Takazudo",
    description: "DIY modular synth case done",
    created_at: "2025-10-18T12:03:09.859Z",
    hashtags: [
      "#synthlife",
      "#electronicmusic",
      "#DIY",
      "#synthcase",
      "#DIYproject",
      "#modularsynthesizer",
      "#homestudio",
      "#studiosetup",
    ],
  },
  {
    slug: "zb40-green-a-4",
    imageAlt: "",
    blurhash: "UUM8r[5Y$]I[2ujFGHW;}YWCV{kXE*oIWrjs",
    user: "Alice",
    description: "My workspace is complete",
    created_at: "2024-03-23T14:50:32.407Z",
    hashtags: [
      "#eurorack",
      "#DIYaudio",
      "#modularsynth",
      "#synth",
      "#rackcase",
      "#analogsynth",
      "#gearpost",
      "#modularsynthesizer",
      "#synthcase",
    ],
  },
  {
    slug: "zb40-green-a-5",
    imageAlt: "",
    blurhash: "UUL3~dEj$]V@X5agRlNd}WV[RlR-E+bHWqoe",
    user: "Alice",
    description: "Perfect fit for my modules",
    created_at: "2025-11-05T18:36:28.925Z",
    hashtags: ["#geartalk", "#woodworking", "#maker", "#studiosetup"],
  },
  {
    slug: "zb40-green-b-2",
    imageAlt: "",
    blurhash: "UFL51W0K.mD%~W9FIo?HXS%MR*%2x]V?-pRj",
    user: "Bob",
    description: "The perfect size for my needs",
    created_at: "2024-11-04T10:34:32.531Z",
    hashtags: [
      "#rackcase",
      "#synth",
      "#synthesizer",
      "#musicproduction",
      "#DIYproject",
      "#eurorack",
      "#synthcase",
      "#electronicmusic",
    ],
  },
  {
    slug: "zb40-green-b-3",
    imageAlt: "",
    blurhash: "UQEysZ?a9Zofo~V[j?e-kYoLj@xtIVt6j[NH",
    user: "Takazudo",
    description: "Love the finish on this one",
    created_at: "2024-04-15T21:13:47.802Z",
    hashtags: [
      "#gearpost",
      "#maker",
      "#DIYproject",
      "#synthlife",
      "#eurorack",
      "#synthcase",
      "#rackcase",
      "#studiosetup",
      "#eurorack",
      "#modularsynthesizer",
    ],
  },
  {
    slug: "zb40-green-a-2",
    imageAlt: "",
    blurhash: "UTMsq|H?s8Mx7,oJaKVs%#bFr:oy-9ofR-bv",
    user: "Alice",
    description: "Working on my dream setup",
    created_at: "2025-07-09T04:53:17.792Z",
    hashtags: [
      "#homestudio",
      "#synthcase",
      "#eurorack",
      "#modularsynth",
      "#gearpost",
    ],
  },
  {
    slug: "zb40-green-a-3",
    imageAlt: "",
    blurhash: "UQM%xY}[$]NI1MjFKORUCkNcVrWq#8oeWra|",
    user: "Takazudo",
    description: "My workspace is complete",
    created_at: "2025-05-23T12:03:34.730Z",
    hashtags: [
      "#woodworking",
      "#DIY",
      "#customcase",
      "#DIYcase",
      "#modularsynthesizer",
      "#modularsynth",
      "#studiosetup",
      "#maker",
    ],
  },
  {
    slug: "zb40-green-b-4",
    imageAlt: "",
    blurhash: "UCH_7J_4RPnOSPIW00^%e8-:R+N{aKn%D*Iq",
    user: "Takazudo",
    description: "Another successful DIY project",
    created_at: "2024-08-04T12:36:13.130Z",
    hashtags: ["#musicgear", "#eurorack", "#customcase", "#handmade"],
  },
  {
    slug: "zb40-green-b-5",
    imageAlt: "",
    blurhash: "UEHA:qH;0Kxt-uE1^+xuE2S$xGM{0Loz-ot7",
    user: "Bob",
    description: "Ready to make some noise",
    created_at: "2025-09-18T05:26:11.025Z",
    hashtags: [
      "#customcase",
      "#synthcase",
      "#DIYcase",
      "#patchcables",
      "#eurorack",
      "#modularsynth",
      "#studioporn",
      "#gearpost",
      "#eurorack",
      "#homestudio",
    ],
  },
  {
    slug: "zb40-green-b-6",
    imageAlt: "",
    blurhash: "UJF~+[4o?v%g~q?bNEae-;WBxu%MD%t7ayM{",
    user: "Takazudo",
    description: "So happy with this build",
    created_at: "2024-09-27T02:07:51.425Z",
    hashtags: [
      "#synth",
      "#synthcase",
      "#DIY",
      "#DIYcase",
      "#analogsynth",
      "#homestudio",
      "#patchcables",
    ],
  },
  {
    slug: "zb40-green-etc-1",
    imageAlt: "",
    blurhash: "UCKd3c~q%h.8x[?bRjIAxuj[t6M{E1t7RjRj",
    user: "Takazudo",
    description: "DIY modular synth case done",
    created_at: "2024-09-24T11:08:35.924Z",
    hashtags: [
      "#DIYproject",
      "#musicgear",
      "#customcase",
      "#synth",
      "#gearpost",
      "#DIY",
      "#analogsynth",
      "#homestudio",
      "#rackcase",
    ],
  },
  {
    slug: "zb40-misc-01",
    imageAlt: "",
    blurhash: "UOGb54_NM{xu_NIUayRjt8t6fQt7M|WBj[t7",
    user: "Takazudo",
    description: "Ready to make some noise",
    created_at: "2024-04-02T23:30:47.745Z",
    hashtags: [
      "#synthlife",
      "#eurorack",
      "#homestudio",
      "#synthesizer",
      "#DIYproject",
      "#gearpost",
      "#patchcables",
    ],
  },
  {
    slug: "zb40-misc-02",
    imageAlt: "",
    blurhash: "UHDs|Y8w?H%MpJtRRjxu00%M%MM{~qM{xuD%",
    user: "Alice",
    description: "Built this beauty over the weekend",
    created_at: "2025-08-29T10:18:05.917Z",
    hashtags: ["#synthcase", "#modularsynthesizer", "#handmade"],
  },
  {
    slug: "zb40-misc-03",
    imageAlt: "",
    blurhash: "UjLqP]xuofNGxujuj[Rj%MofofWAIAWBt7t7",
    user: "Alice",
    description: "My modular journey continues",
    created_at: "2024-03-18T17:24:42.359Z",
    hashtags: [
      "#eurorack",
      "#customcase",
      "#studioporn",
      "#homestudio",
      "#musicgear",
      "#modularsynthesizer",
    ],
  },
  {
    slug: "zb40-misc-05",
    imageAlt: "",
    blurhash: "U9D0J200-;_4.8~q_3xut7t7xuM|~qM{xuD%",
    user: "Alice",
    description: "DIY modular synth case done",
    created_at: "2024-10-07T18:14:40.276Z",
    hashtags: ["#handmade", "#modularsynthesizer", "#eurorack", "#DIY"],
  },
  {
    slug: "zb40-misc-07",
    imageAlt: "",
    blurhash: "UFDJaA00M{%N%Mt8xu-;IUt7xut7^+WBt7M{",
    user: "Alice",
    description: "Proud of this one",
    created_at: "2025-08-16T19:45:34.143Z",
    hashtags: [
      "#customcase",
      "#electronicmusic",
      "#handmade",
      "#maker",
      "#musicproduction",
      "#analogsynth",
      "#DIYproject",
      "#eurorack",
    ],
  },
  {
    slug: "zb40-misc-08",
    imageAlt: "",
    blurhash: "UBD0Td00-;%N^*%N%Mxut7xuM{NG~qofWBM{",
    user: "Bob",
    description: "Hand-crafted with love",
    created_at: "2025-04-04T08:52:50.904Z",
    hashtags: ["#analogsynth", "#maker", "#eurorack", "#eurorack"],
  },
  {
    slug: "zb40-misc-09",
    imageAlt: "",
    blurhash: "URCjc$ayM{of~qj[of%Mayxut7Rjt6WBayay",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-08-23T16:19:06.745Z",
    hashtags: [
      "#musicproduction",
      "#DIY",
      "#synth",
      "#modular",
      "#DIYaudio",
      "#eurorack",
      "#maker",
      "#modularsynth",
      "#woodworking",
      "#homestudio",
    ],
  },
  {
    slug: "zb40-misc-11",
    imageAlt: "",
    blurhash: "U9ECUZ00~q.8_3~q-;xuD%xuWBIU~qofM{M{",
    user: "Takazudo",
    description: "Custom case for my modules",
    created_at: "2024-08-03T02:20:03.856Z",
    hashtags: ["#DIY", "#geartalk", "#analogsynth", "#synthcase", "#rackcase"],
  },
  {
    slug: "zb40-misc-13",
    imageAlt: "",
    blurhash: "U8C?xBxu00~q~qRjRjD%%Mt7IUxu%Mxu9FIU",
    user: "Takazudo",
    description: "This case sounds incredible",
    created_at: "2024-09-08T06:48:50.726Z",
    hashtags: [
      "#electronicmusic",
      "#gearpost",
      "#musicgear",
      "#homestudio",
      "#eurorack",
    ],
  },
  {
    slug: "zb40-misc-14",
    imageAlt: "",
    blurhash: "UOF#:Gt6xuWC~qofWBWCM{ofWBWC%Mt7ofof",
    user: "Alice",
    description: "Another successful DIY project",
    created_at: "2024-12-21T14:34:40.209Z",
    hashtags: [
      "#patchcables",
      "#modularsynthesizer",
      "#studiosetup",
      "#customcase",
      "#homestudio",
    ],
  },
  {
    slug: "zb40-orange-a-1",
    imageAlt: "",
    blurhash: "UTKw{yE3%$oJ9ZoLWCkDt*o0V@t7-ooLR*ad",
    user: "Bob",
    description: "Built this beauty over the weekend",
    created_at: "2025-09-10T11:05:08.080Z",
    hashtags: [
      "#studioporn",
      "#eurorack",
      "#gearpost",
      "#modularsynth",
      "#synth",
      "#synthlife",
      "#handmade",
      "#modular",
      "#homestudio",
    ],
  },
  {
    slug: "zb40-orange-a-2",
    imageAlt: "",
    blurhash: "UTL3~ZEj$^V@YeagRlNe}WV{RkR-E*bHWroe",
    user: "Bob",
    description: "My modular journey continues",
    created_at: "2024-02-05T17:38:07.442Z",
    hashtags: ["#synthcase", "#modular", "#eurorack"],
  },
  {
    slug: "zb40-orange-a-3",
    imageAlt: "",
    blurhash: "UVM8r{5Y$]I[2ujFGHS$}YWDV{kVE*oIWsjs",
    user: "Alice",
    description: "Been working on this for months",
    created_at: "2024-11-24T20:26:07.214Z",
    hashtags: [
      "#synthlife",
      "#DIYcase",
      "#patchcables",
      "#modularsynth",
      "#electronicmusic",
      "#handmade",
      "#eurorack",
      "#maker",
      "#studiosetup",
    ],
  },
  {
    slug: "zb40-orange-a-4",
    imageAlt: "",
    blurhash: "UOM%xY|z$]NI1MjFKOQ-CkNeVrWq#8oeWraK",
    user: "Alice",
    description: "Working on my dream setup",
    created_at: "2025-07-03T12:42:13.455Z",
    hashtags: [
      "#analogsynth",
      "#maker",
      "#synthcase",
      "#musicproduction",
      "#patchcables",
      "#modularsynth",
      "#synth",
      "#synthesizer",
      "#DIYcase",
      "#DIYproject",
    ],
  },
  {
    slug: "zb40-orange-a-5",
    imageAlt: "",
    blurhash: "UUMtG;H?vgN{9aoJa}Vs%#bHr:oy-9ofR-bx",
    user: "Alice",
    description: "DIY modular synth case done",
    created_at: "2024-10-16T08:01:38.809Z",
    hashtags: [
      "#DIY",
      "#handmade",
      "#woodworking",
      "#electronicmusic",
      "#DIYproject",
      "#maker",
    ],
  },
  {
    slug: "zb40-orange-b-2",
    imageAlt: "",
    blurhash: "UEL51W0K-TE2~V9FIo?HXnrqWX%1x[V@-;Rk",
    user: "Bob",
    description: "DIY eurorack at its finest",
    created_at: "2024-03-25T00:08:51.329Z",
    hashtags: ["#DIYaudio", "#geartalk", "#synthcase"],
  },
  {
    slug: "zb40-orange-b-3",
    imageAlt: "",
    blurhash: "UNEysZ}F9YV@pdWVj[ayVtf+f7xvE0s:fka#",
    user: "Bob",
    description: "Proud of this one",
    created_at: "2024-12-16T22:32:29.508Z",
    hashtags: [
      "#synthesizer",
      "#DIYproject",
      "#woodworking",
      "#customcase",
      "#musicgear",
      "#modularsynthesizer",
      "#electronicmusic",
      "#analogsynth",
    ],
  },
  {
    slug: "zb40-orange-b-4",
    imageAlt: "",
    blurhash: "UCH_7K_NRPnOT{IW00_NuPTLQ-NH9bWW9ExG",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-07-06T06:53:32.379Z",
    hashtags: ["#studiosetup", "#geartalk", "#woodworking", "#electronicmusic"],
  },
  {
    slug: "zb40-orange-b-5",
    imageAlt: "",
    blurhash: "UCHA:qH?0Kxt_NE1?bxuE1S$xGM{0Loz_Nt7",
    user: "Bob",
    description: "Another successful DIY project",
    created_at: "2025-07-02T13:22:36.972Z",
    hashtags: ["#patchcables", "#eurorack", "#synth", "#DIYcase"],
  },
  {
    slug: "zb40-orange-b-6",
    imageAlt: "",
    blurhash: "UIF~*n4o?v%g~q?bNEae-;W=xu%MD%t6ayM{",
    user: "Alice",
    description: "Custom panel design worked perfectly",
    created_at: "2024-07-14T06:04:39.848Z",
    hashtags: [
      "#patchcables",
      "#eurorack",
      "#DIYproject",
      "#modularsynthesizer",
      "#maker",
      "#gearpost",
      "#homestudio",
      "#synthesizer",
    ],
  },
  {
    slug: "zb40-orange-etc-1",
    imageAlt: "",
    blurhash: "UAKd3d~q.8.8D%-;RjIATOj[t6M{E1t7RjRj",
    user: "Bob",
    description: "The perfect size for my needs",
    created_at: "2025-01-12T16:24:37.617Z",
    hashtags: ["#synth", "#geartalk", "#studiosetup"],
  },
  {
    slug: "zb40-parts-1",
    imageAlt: "",
    blurhash: "U4DvO3_300%M~qxuM{xu%MRjayRjD%ayM{%M",
    user: "Takazudo",
    description: "My workspace is complete",
    created_at: "2024-05-14T16:43:04.027Z",
    hashtags: ["#maker", "#studiosetup", "#synthlife", "#woodworking"],
  },
  {
    slug: "zb40-photo",
    imageAlt: "",
    blurhash: "UDC?xAD%~q%N^+%MM{xuD%ofofRj%Mt8Rjxu",
    user: "Bob",
    description: "Built this beauty over the weekend",
    created_at: "2024-03-31T17:19:22.681Z",
    hashtags: [
      "#homestudio",
      "#modularsynth",
      "#rackcase",
      "#geartalk",
      "#studiosetup",
      "#maker",
      "#patchcables",
      "#modularsynthesizer",
    ],
  },
  {
    slug: "zb40-red-a-1",
    imageAlt: "",
    blurhash: "URJtSDE4oJj[M{oLV[kCxZoeayj[s:oLoead",
    user: "Takazudo",
    description: "Love the finish on this one",
    created_at: "2024-01-26T08:59:03.395Z",
    hashtags: [
      "#maker",
      "#DIYproject",
      "#synthcase",
      "#modularsynth",
      "#synthlife",
      "#geartalk",
    ],
  },
  {
    slug: "zb40-red-a-2",
    imageAlt: "",
    blurhash: "URL3~aE3$]V@YeagRlNe}WV[RlQ.E*bHWqoe",
    user: "Alice",
    description: "My latest eurorack creation",
    created_at: "2025-10-08T11:27:54.625Z",
    hashtags: ["#eurorack", "#customcase", "#modular", "#synthesizer"],
  },
  {
    slug: "zb40-red-a-3",
    imageAlt: "",
    blurhash: "UTM8r[5S$]I[2ujFGHS$}YWAV{kXENoIWsjs",
    user: "Alice",
    description: "Great project to work on",
    created_at: "2025-02-13T13:53:16.458Z",
    hashtags: ["#synthlife", "#musicgear", "#studiosetup"],
  },
  {
    slug: "zb40-red-a-4",
    imageAlt: "",
    blurhash: "UNM%xY}W$]NI1MjFKORTCkNeVrWq#8oeWraK",
    user: "Alice",
    description: "Built this beauty over the weekend",
    created_at: "2024-08-23T15:16:02.322Z",
    hashtags: ["#handmade", "#DIYaudio", "#gearpost"],
  },
  {
    slug: "zb40-red-a-5",
    imageAlt: "",
    blurhash: "UTMsq|Gls8N{7,oJaKVs%#bGr:o#:*ofR-bv",
    user: "Bob",
    description: "Finally got my rack layout perfect",
    created_at: "2024-09-26T15:58:37.306Z",
    hashtags: [
      "#synthlife",
      "#synthcase",
      "#electronicmusic",
      "#customcase",
      "#woodworking",
    ],
  },
  {
    slug: "zb40-red-b-2",
    imageAlt: "",
    blurhash: "UFL51Y0K.mD%~V9FIo?HXS%MWX%2x]V@-pRj",
    user: "Takazudo",
    description: "Another successful DIY project",
    created_at: "2024-03-24T18:02:26.328Z",
    hashtags: [
      "#DIYproject",
      "#musicgear",
      "#DIY",
      "#synthlife",
      "#electronicmusic",
      "#modularsynth",
      "#homestudio",
      "#studioporn",
    ],
  },
  {
    slug: "zb40-red-b-3",
    imageAlt: "",
    blurhash: "UOEysZ?a9ZV@o~VZj?afkYoej@xtIVt6j[NH",
    user: "Alice",
    description: "My modular journey continues",
    created_at: "2024-05-04T23:24:50.462Z",
    hashtags: [
      "#musicgear",
      "#synthlife",
      "#DIYaudio",
      "#DIYproject",
      "#maker",
      "#DIYcase",
      "#customcase",
      "#studiosetup",
      "#eurorack",
      "#homestudio",
    ],
  },
  {
    slug: "zb40-red-b-4",
    imageAlt: "",
    blurhash: "UAH_7J_4ROnOS}IW00^%uPTLQ-N{9bWW9ExG",
    user: "Takazudo",
    description: "Another successful DIY project",
    created_at: "2024-06-27T01:29:30.725Z",
    hashtags: ["#eurorack", "#DIYproject", "#synthcase", "#DIYaudio"],
  },
  {
    slug: "zb40-red-b-5",
    imageAlt: "",
    blurhash: "UEHA:qHA0Kxt-uE1^+xuE2S$xGM{0Koz-ot7",
    user: "Takazudo",
    description: "Finally got my rack layout perfect",
    created_at: "2025-01-27T11:34:28.429Z",
    hashtags: [
      "#DIYcase",
      "#eurorack",
      "#patchcables",
      "#DIYproject",
      "#customcase",
      "#modularsynthesizer",
      "#handmade",
      "#DIY",
      "#musicgear",
    ],
  },
  {
    slug: "zb40-red-b-6",
    imageAlt: "",
    blurhash: "UJF~*c4o?v%g~q?bNEae:=WBxu%MD%t7ayM{",
    user: "Takazudo",
    description: "Another successful DIY project",
    created_at: "2024-06-14T07:51:18.238Z",
    hashtags: [
      "#handmade",
      "#DIYaudio",
      "#analogsynth",
      "#synthlife",
      "#rackcase",
      "#gearpost",
      "#woodworking",
      "#musicproduction",
      "#homestudio",
      "#synthcase",
    ],
  },
  {
    slug: "zb40-red-etc-1",
    imageAlt: "",
    blurhash: "UAKd3c~q.8.8D%-;RjIATLj[t6M{E1t7RjRj",
    user: "Takazudo",
    description: "Time to patch some cables",
    created_at: "2025-10-04T09:43:30.358Z",
    hashtags: ["#DIYcase", "#homestudio", "#synth", "#modular"],
  },
  {
    slug: "zb40-variations",
    imageAlt: "",
    blurhash: "UOH.M{_3t7D%.8%MWBt7Rjt7t7%M%Mt7Rjay",
    user: "Takazudo",
    description: "Hand-crafted with love",
    created_at: "2025-09-14T02:17:54.051Z",
    hashtags: ["#eurorack", "#modularsynthesizer", "#DIYproject"],
  },
  {
    slug: "zb40l-01-1",
    imageAlt: "",
    blurhash: "UCG8cV$v00?H~AH;NGKj^5-;9HWU_xMzX5e=",
    user: "Takazudo",
    description: "Ready to make some noise",
    created_at: "2024-11-21T07:10:14.225Z",
    hashtags: ["#DIYaudio", "#synthlife", "#eurorack", "#modular"],
  },
  {
    slug: "zb40l-01-2",
    imageAlt: "",
    blurhash: "UCFr,?-:8xH;~BW=V^xa%0-;j^D*I^xVadsp",
    user: "Bob",
    description: "My modular journey continues",
    created_at: "2025-08-21T10:33:58.883Z",
    hashtags: [
      "#modularsynth",
      "#analogsynth",
      "#eurorack",
      "#electronicmusic",
      "#rackcase",
      "#DIY",
    ],
  },
  {
    slug: "zb40l-02-1",
    imageAlt: "",
    blurhash: "UIE:Y3IU%1~VR%ozR*of01ogNfRjxZoLoeWq",
    user: "Takazudo",
    description: "My synth corner is looking good",
    created_at: "2025-10-17T05:15:23.023Z",
    hashtags: [
      "#synthlife",
      "#studiosetup",
      "#patchcables",
      "#synthesizer",
      "#homestudio",
      "#synth",
    ],
  },
  {
    slug: "zb40l-02-2",
    imageAlt: "",
    blurhash: "UHFiURRj.9~qofWBoet600WBE2of~pt7D%WB",
    user: "Alice",
    description: "Time to patch some cables",
    created_at: "2024-10-25T09:35:49.940Z",
    hashtags: [
      "#DIYaudio",
      "#studiosetup",
      "#synthesizer",
      "#customcase",
      "#synthcase",
      "#DIYcase",
      "#DIY",
    ],
  },
  {
    slug: "zb40l-03-1",
    imageAlt: "",
    blurhash: "UHDSvQIU9a~V%MoL9FRkIUs:M{s:RkoLWBjZ",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-12-04T05:01:01.779Z",
    hashtags: [
      "#studiosetup",
      "#studioporn",
      "#maker",
      "#eurorack",
      "#eurorack",
      "#synthcase",
      "#handmade",
      "#modular",
      "#rackcase",
      "#gearpost",
    ],
  },
  {
    slug: "zb40l-03-2",
    imageAlt: "",
    blurhash: "UHEo^YRj.8~qoeWBozt600WBE1of~pt7D%WB",
    user: "Takazudo",
    description: "DIY eurorack at its finest",
    created_at: "2024-10-27T11:45:12.118Z",
    hashtags: [
      "#handmade",
      "#analogsynth",
      "#homestudio",
      "#rackcase",
      "#musicproduction",
      "#woodworking",
      "#synthesizer",
      "#studioporn",
      "#modularsynth",
    ],
  },
  {
    slug: "zb40l-04-1",
    imageAlt: "",
    blurhash: "UIDv{G-9~W?F^$E2xuRjRPE1M|xax@xu%1xu",
    user: "Bob",
    description: "My modular journey continues",
    created_at: "2024-02-19T01:26:51.292Z",
    hashtags: [
      "#customcase",
      "#maker",
      "#DIYcase",
      "#eurorack",
      "#eurorack",
      "#woodworking",
      "#DIYproject",
      "#modularsynthesizer",
    ],
  },
  {
    slug: "zb40l-04-2",
    imageAlt: "",
    blurhash: "UAF#:GbIafD%~pofWBWBRjt8RjWBWBofj[j[",
    user: "Alice",
    description: "Built this beauty over the weekend",
    created_at: "2024-01-10T21:40:50.562Z",
    hashtags: [
      "#electronicmusic",
      "#studiosetup",
      "#analogsynth",
      "#modularsynthesizer",
      "#musicproduction",
      "#DIY",
      "#studioporn",
      "#synth",
    ],
  },
  {
    slug: "zb40l-photos-1",
    imageAlt: "",
    blurhash: "UDFOi*0x-A%0~U-Ot6ot9~$%S3j?.8NG9uRP",
    user: "Bob",
    description: "Ready to make some noise",
    created_at: "2024-04-04T04:33:58.312Z",
    hashtags: [
      "#DIY",
      "#eurorack",
      "#synthesizer",
      "#studiosetup",
      "#customcase",
      "#synth",
      "#gearpost",
      "#patchcables",
      "#DIYproject",
      "#eurorack",
    ],
  },
  {
    slug: "zb40l-photos-2",
    imageAlt: "",
    blurhash: "UIG9UZ~T9@9y}[I=R,I[EnE2xGoyEMxCWWs-",
    user: "Takazudo",
    description: "Love how this turned out",
    created_at: "2025-01-31T04:59:32.396Z",
    hashtags: [
      "#musicgear",
      "#customcase",
      "#analogsynth",
      "#DIYcase",
      "#geartalk",
      "#maker",
      "#woodworking",
      "#DIY",
      "#modularsynth",
    ],
  },
  {
    slug: "zb40lite-dual-3",
    imageAlt: "",
    blurhash: "U9G[m*t64.s,~qWB9HM^E2t7M|WBD%WBD%t7",
    user: "Bob",
    description: "This setup is pure joy",
    created_at: "2024-07-12T09:43:11.006Z",
    hashtags: [
      "#electronicmusic",
      "#homestudio",
      "#modularsynth",
      "#eurorack",
      "#musicproduction",
      "#synthlife",
      "#analogsynth",
      "#musicgear",
      "#woodworking",
    ],
  },
  {
    slug: "zb40lite-variations-1",
    imageAlt: "",
    blurhash: "UHGlCiD%00D%?bfPM{xuoffQj[xu%MWBxut6",
    user: "Bob",
    description: "Built this beauty over the weekend",
    created_at: "2025-01-14T16:05:38.618Z",
    hashtags: [
      "#electronicmusic",
      "#synthcase",
      "#studioporn",
      "#eurorack",
      "#analogsynth",
    ],
  },
  {
    slug: "zb40lite-zoom-5",
    imageAlt: "",
    blurhash: "UDF=u9^%-Un,EgEfxCayFe9t$%Sz~D%2IT%2",
    user: "Bob",
    description: "My modular case is finally complete",
    created_at: "2024-08-27T16:11:40.292Z",
    hashtags: [
      "#synthesizer",
      "#musicproduction",
      "#handmade",
      "#synth",
      "#woodworking",
      "#eurorack",
      "#DIYcase",
      "#DIY",
      "#homestudio",
    ],
  },
  {
    slug: "zb40lite-zoom-6",
    imageAlt: "",
    blurhash: "U9H_DZt6Mzxu9Jxu_3RjD*RjM|RjD%WBM{M{",
    user: "Takazudo",
    description: "This build exceeded my expectations",
    created_at: "2025-03-15T11:21:47.364Z",
    hashtags: [
      "#eurorack",
      "#studiosetup",
      "#DIYcase",
      "#musicproduction",
      "#DIY",
      "#geartalk",
      "#modularsynth",
    ],
  },
  {
    slug: "zb40lite02-3",
    imageAlt: "",
    blurhash: "UEG[m*xu4.s:~qR*9Gt7E2t7M{RjD%xuD%t7",
    user: "Alice",
    description: "Clean cable management achieved",
    created_at: "2024-06-02T02:26:41.675Z",
    hashtags: [
      "#eurorack",
      "#handmade",
      "#modular",
      "#synthcase",
      "#studioporn",
      "#studiosetup",
    ],
  },
  {
    slug: "zb60-3panels-03",
    imageAlt: "",
    blurhash: "UBEy44~q4nM{~q-;IUt7D%t7xuM{~qIURjay",
    user: "Takazudo",
    description: "Ready to make some noise",
    created_at: "2025-08-18T16:02:53.762Z",
    hashtags: [
      "#modularsynth",
      "#electronicmusic",
      "#maker",
      "#modular",
      "#DIYcase",
      "#handmade",
      "#studiosetup",
    ],
  },
  {
    slug: "zb60-all-02",
    imageAlt: "",
    blurhash: "UIGlvnrrt7kC0MRRROn$rYMwR4V?rpM{%2%2",
    user: "Takazudo",
    description: "Sweet new case for the studio",
    created_at: "2025-11-07T03:52:04.794Z",
    hashtags: [
      "#musicproduction",
      "#handmade",
      "#customcase",
      "#homestudio",
      "#woodworking",
    ],
  },
  {
    slug: "zb60-all-03",
    imageAlt: "",
    blurhash: "UJHBk*t6M{V=03M_WEoJE6M|t6f+Mxj]oet7",
    user: "Takazudo",
    description: "Finally got my rack layout perfect",
    created_at: "2024-11-25T07:58:52.703Z",
    hashtags: [
      "#patchcables",
      "#DIY",
      "#synthcase",
      "#studioporn",
      "#modular",
      "#gearpost",
      "#DIYcase",
    ],
  },
  {
    slug: "zb60-all-04",
    imageAlt: "",
    blurhash: "UEHeg*S#Ip9v02D*a{Nd$xjZn#NFD*t6E2%1",
    user: "Alice",
    description: "My workspace is complete",
    created_at: "2024-10-25T10:06:41.424Z",
    hashtags: [
      "#musicgear",
      "#DIYcase",
      "#synth",
      "#homestudio",
      "#synthcase",
      "#modularsynthesizer",
      "#studioporn",
      "#musicproduction",
      "#handmade",
      "#studiosetup",
    ],
  },
  {
    slug: "zb60-all-05",
    imageAlt: "",
    blurhash: "UDF6IX0100-:-=D%M{xuWBxuxuof~qRjM{Rj",
    user: "Alice",
    description: "Proud of this one",
    created_at: "2024-01-01T00:37:17.752Z",
    hashtags: [
      "#modular",
      "#musicgear",
      "#analogsynth",
      "#DIYaudio",
      "#DIY",
      "#rackcase",
      "#synthlife",
      "#handmade",
    ],
  },
  {
    slug: "zb60-combine-2",
    imageAlt: "",
    blurhash: "U8ECUZ00~q.8_3~q9FxuD%xuWBIU~qofM{M{",
    user: "Alice",
    description: "Love the finish on this one",
    created_at: "2025-08-31T01:44:58.013Z",
    hashtags: [
      "#DIY",
      "#handmade",
      "#customcase",
      "#DIYcase",
      "#homestudio",
      "#studiosetup",
      "#woodworking",
      "#patchcables",
    ],
  },
  {
    slug: "zb60-combine-5",
    imageAlt: "",
    blurhash: "UADS*{~q00D%4nRjM{t7%Mt7xuRj-;t7xuRj",
    user: "Alice",
    description: "Custom panel design worked perfectly",
    created_at: "2024-03-27T21:25:03.937Z",
    hashtags: [
      "#DIYproject",
      "#customcase",
      "#geartalk",
      "#electronicmusic",
      "#DIY",
      "#musicproduction",
      "#modularsynthesizer",
      "#studioporn",
      "#synthcase",
      "#woodworking",
    ],
  },
  {
    slug: "zb60-green-02",
    imageAlt: "",
    blurhash: "UPF5hr}Y$]NH3=jaR%Vs}Wrsr;o#JnofR,bH",
    user: "Takazudo",
    description: "So happy with this build",
    created_at: "2024-12-26T12:39:13.975Z",
    hashtags: ["#DIYproject", "#customcase", "#musicproduction"],
  },
  {
    slug: "zb60-green-01",
    imageAlt: "",
    blurhash: "UOJtSLE3oJj[NEoLV[kCwIoej[j[r;oeoead",
    user: "Takazudo",
    description: "Love the finish on this one",
    created_at: "2025-08-18T03:40:06.327Z",
    hashtags: ["#modularsynthesizer", "#rackcase", "#DIY"],
  },
  {
    slug: "zb60-green-03",
    imageAlt: "",
    blurhash: "UQE~YvEjbwV^8woJxYRkX7o#V[NG%go#NGj?",
    user: "Bob",
    description: "This case sounds incredible",
    created_at: "2024-02-08T03:57:23.172Z",
    hashtags: [
      "#DIY",
      "#maker",
      "#woodworking",
      "#musicgear",
      "#musicproduction",
    ],
  },
  {
    slug: "zb60-open-assembly-1",
    imageAlt: "",
    blurhash: "UADcT{%M~q-;?bWB-;M{M{WBxuWB~qWBRjRj",
    user: "Bob",
    description: "Custom case for my modules",
    created_at: "2024-04-29T08:56:59.514Z",
    hashtags: ["#handmade", "#DIYproject", "#synthesizer", "#modularsynth"],
  },
  {
    slug: "zb60-open-assembly-2",
    imageAlt: "",
    blurhash: "UBD0J3%M~q-;?bIU%MM{D%M{xuWB~qWBRjRj",
    user: "Alice",
    description: "Finally got my rack layout perfect",
    created_at: "2025-07-22T19:36:55.551Z",
    hashtags: [
      "#modular",
      "#analogsynth",
      "#synthesizer",
      "#eurorack",
      "#woodworking",
    ],
  },
  {
    slug: "zb60-open-assembly-rail-3",
    imageAlt: "",
    blurhash: "UADcT{xu~q9F?b%MRjM{M{RjxuM{~qWBRjRj",
    user: "Bob",
    description: "Another successful DIY project",
    created_at: "2024-10-10T08:55:40.092Z",
    hashtags: [
      "#patchcables",
      "#synth",
      "#homestudio",
      "#modular",
      "#handmade",
      "#synthcase",
      "#electronicmusic",
      "#DIYcase",
      "#synthesizer",
    ],
  },
  {
    slug: "zb60-open-high-view-a",
    imageAlt: "",
    blurhash: "ULDS*{~q00D%4nRjRjRj%Mt7xuRj-;RjxuRj",
    user: "Alice",
    description: "Custom case for my modules",
    created_at: "2025-07-13T03:38:00.149Z",
    hashtags: [
      "#DIYaudio",
      "#DIY",
      "#musicgear",
      "#homestudio",
      "#geartalk",
      "#DIYcase",
    ],
  },
  {
    slug: "zb60-open-high-view-b",
    imageAlt: "",
    blurhash: "UHDS*t~q00%M-;RjRjRjD%M{xuRj%MRjxuay",
    user: "Takazudo",
    description: "Custom panel design worked perfectly",
    created_at: "2025-11-02T10:37:37.727Z",
    hashtags: [
      "#musicproduction",
      "#woodworking",
      "#modularsynth",
      "#rackcase",
      "#gearpost",
      "#eurorack",
      "#DIYaudio",
      "#synthlife",
    ],
  },
  {
    slug: "zb60-open-assembly-rail-1",
    imageAlt: "",
    blurhash: "UBDcT{%M~q-;?bt7-;M{M{WBxuWB~qWBRjRj",
    user: "Takazudo",
    description: "This case sounds incredible",
    created_at: "2024-04-29T17:52:00.372Z",
    hashtags: [
      "#DIYcase",
      "#handmade",
      "#musicgear",
      "#studioporn",
      "#synthcase",
      "#eurorack",
      "#eurorack",
      "#homestudio",
      "#studiosetup",
    ],
  },
  {
    slug: "zb60-open-assembly-rail-2",
    imageAlt: "",
    blurhash: "UBD0J2%M~q%M?bIU%MM{D%M{xuWB~qWBRjRj",
    user: "Alice",
    description: "Proud of this one",
    created_at: "2025-05-31T18:34:18.001Z",
    hashtags: [
      "#homestudio",
      "#maker",
      "#modular",
      "#synthlife",
      "#studioporn",
      "#synthcase",
      "#electronicmusic",
    ],
  },
  {
    slug: "zb60-open-top-view-a",
    imageAlt: "",
    blurhash: "UADcT{xu~q9F~qRjRjM{M{RjxuM{~qWBRjRj",
    user: "Takazudo",
    description: "Just finished this amazing build!",
    created_at: "2025-08-08T07:25:03.455Z",
    hashtags: [
      "#synth",
      "#analogsynth",
      "#woodworking",
      "#patchcables",
      "#handmade",
      "#gearpost",
      "#modular",
    ],
  },
  {
    slug: "zb60-open-top-view-b",
    imageAlt: "",
    blurhash: "UBDS*t~q00%M-;RjRjRjD%Rjt7Rj-;RjxuRj",
    user: "Alice",
    description: "My modular journey continues",
    created_at: "2024-07-01T10:39:38.780Z",
    hashtags: ["#modularsynthesizer", "#woodworking", "#homestudio"],
  },
  {
    slug: "zb60-open-top-view-modules",
    imageAlt: "",
    blurhash: "UEECnv-;~q9F~q%M%MM{D%xuRjRj%Mt7RjRj",
    user: "Takazudo",
    description: "DIY modular synth case done",
    created_at: "2024-09-10T08:46:26.207Z",
    hashtags: [
      "#handmade",
      "#analogsynth",
      "#synth",
      "#eurorack",
      "#customcase",
    ],
  },
  {
    slug: "zb60-open-with-modules",
    imageAlt: "",
    blurhash: "UdH,x4v}$g-U}sR-sSs:}TofW=jZwvSOoeoJ",
    user: "Takazudo",
    description: "Custom panel design worked perfectly",
    created_at: "2024-12-30T08:12:03.993Z",
    hashtags: ["#synthlife", "#analogsynth", "#handmade"],
  },
  {
    slug: "zb60-open-with-modules2",
    imageAlt: "",
    blurhash: "UAD8nI}6T0?Gu3NYxB%Mt,,-%2xs^h$yxZ%0",
    user: "Bob",
    description: "The perfect size for my needs",
    created_at: "2025-10-27T06:25:57.149Z",
    hashtags: [
      "#geartalk",
      "#gearpost",
      "#DIYaudio",
      "#musicproduction",
      "#studiosetup",
      "#DIYproject",
      "#modularsynthesizer",
      "#patchcables",
    ],
  },
  {
    slug: "zb60-orange-01",
    imageAlt: "",
    blurhash: "UOJkxeD$r?kD0KagWBkDvzoJj[j[smoeoead",
    user: "Bob",
    description: "So happy with this build",
    created_at: "2024-11-10T07:08:36.542Z",
    hashtags: [
      "#electronicmusic",
      "#handmade",
      "#synthesizer",
      "#modularsynthesizer",
      "#studiosetup",
      "#synthcase",
      "#maker",
      "#geartalk",
    ],
  },
  {
    slug: "zb60-orange-02",
    imageAlt: "",
    blurhash: "UPF5hr}W$^NH3=jaR%Vs}Wrsr:o#I.oeQ.bH",
    user: "Alice",
    description: "Custom panel design worked perfectly",
    created_at: "2024-09-27T13:24:01.796Z",
    hashtags: [
      "#customcase",
      "#studiosetup",
      "#studioporn",
      "#DIYcase",
      "#synthesizer",
      "#synthcase",
      "#eurorack",
    ],
  },
  {
    slug: "zb60-orange-03",
    imageAlt: "",
    blurhash: "UPE~YvD$bwV^8woJxYRkX7o#V[NG%go#NGj[",
    user: "Alice",
    description: "Another successful DIY project",
    created_at: "2024-11-28T14:35:03.164Z",
    hashtags: [
      "#DIY",
      "#analogsynth",
      "#synthesizer",
      "#modularsynth",
      "#modularsynthesizer",
      "#patchcables",
      "#customcase",
    ],
  },
  {
    slug: "zb60-panels",
    imageAlt: "",
    blurhash: "UDDvYV%2~qxu4.t7RjM{~qxuM{WBxuWBM{of",
    user: "Bob",
    description: "Clean cable management achieved",
    created_at: "2024-12-04T06:17:57.469Z",
    hashtags: [
      "#geartalk",
      "#eurorack",
      "#DIY",
      "#DIYproject",
      "#woodworking",
      "#customcase",
      "#rackcase",
      "#handmade",
      "#modularsynth",
      "#homestudio",
    ],
  },
  {
    slug: "zb60-red-01",
    imageAlt: "",
    blurhash: "UMJkxiD$r?kD0KaeWBkDvzj^j[j[smoeoead",
    user: "Takazudo",
    description: "Ready to make some noise",
    created_at: "2025-03-28T18:31:35.466Z",
    hashtags: [
      "#geartalk",
      "#DIYproject",
      "#synthesizer",
      "#gearpost",
      "#modularsynth",
      "#electronicmusic",
      "#studiosetup",
      "#studioporn",
    ],
  },
  {
    slug: "zb60-red-02",
    imageAlt: "",
    blurhash: "UPF5is}W$]NH3=jaR%Vs}Wrsr:oJIooJQ.bH",
    user: "Alice",
    description: "Love the finish on this one",
    created_at: "2024-08-11T23:06:25.085Z",
    hashtags: [
      "#gearpost",
      "#DIY",
      "#musicproduction",
      "#customcase",
      "#DIYaudio",
      "#synthlife",
      "#synthcase",
      "#DIYproject",
    ],
  },
  {
    slug: "zb60-red-03",
    imageAlt: "",
    blurhash: "UPE~YvD$bwV^8woJxYRkX7o#V[NG%go#NGj?",
    user: "Bob",
    description: "The perfect size for my needs",
    created_at: "2025-05-14T08:38:33.419Z",
    hashtags: [
      "#handmade",
      "#modular",
      "#eurorack",
      "#synth",
      "#studiosetup",
      "#DIYcase",
    ],
  },
  {
    slug: "zb60-with-modules-01",
    imageAlt: "",
    blurhash: "U9ECo#9F~q%MD%%MRjIU.8IUxuof-;xuofRj",
    user: "Takazudo",
    description: "DIY eurorack at its finest",
    created_at: "2025-09-11T22:14:49.034Z",
    hashtags: ["#geartalk", "#DIYcase", "#studiosetup", "#DIY"],
  },
  {
    slug: "zb60-with-modules-02",
    imageAlt: "",
    blurhash: "UDEfG0xu9F%M?bofof%MM{xuM{of-;xuofWB",
    user: "Alice",
    description: "Finally got my rack layout perfect",
    created_at: "2025-07-01T16:36:47.988Z",
    hashtags: [
      "#synthesizer",
      "#musicproduction",
      "#modularsynth",
      "#maker",
      "#synthcase",
      "#synthlife",
      "#geartalk",
    ],
  },
  {
    slug: "zb60-with-modules-03",
    imageAlt: "",
    blurhash: "UAECUZ00~q%M_3%MIU%M.8%MofRj%MofofRj",
    user: "Alice",
    description: "My modular journey continues",
    created_at: "2025-02-17T02:54:52.537Z",
    hashtags: ["#synthcase", "#patchcables", "#synthlife"],
  },
  {
    slug: "zb60-with-modules-04",
    imageAlt: "",
    blurhash: "UBD0Ta00~q%MIUxuIUM{%Mt7xuRjIUofRjof",
    user: "Takazudo",
    description: "Sweet new case for the studio",
    created_at: "2025-06-16T20:26:52.062Z",
    hashtags: [
      "#analogsynth",
      "#modular",
      "#customcase",
      "#studiosetup",
      "#patchcables",
      "#synthesizer",
      "#synthcase",
      "#synthlife",
      "#homestudio",
      "#rackcase",
    ],
  },
  {
    slug: "zb60-with-modules-06",
    imageAlt: "",
    blurhash: "UBECUZ00~q%M-;M{IU%M9Ft7xuRj-;ofofRj",
    user: "Alice",
    description: "Clean cable management achieved",
    created_at: "2024-04-17T15:13:06.398Z",
    hashtags: [
      "#patchcables",
      "#eurorack",
      "#woodworking",
      "#customcase",
      "#homestudio",
    ],
  },
  {
    slug: "zb60-with-modules-09",
    imageAlt: "",
    blurhash: "UCDcT{%M~q-;xu%MRjM{M{M{xuM{~qWBRjRj",
    user: "Alice",
    description: "This setup is pure joy",
    created_at: "2024-11-29T11:11:13.512Z",
    hashtags: [
      "#patchcables",
      "#homestudio",
      "#handmade",
      "#DIY",
      "#modularsynthesizer",
    ],
  },
  {
    slug: "zb60-with-modules-11",
    imageAlt: "",
    blurhash: "UCF5hr}Y$]NH3=oLR%Vs}YoLr;oJ3#oeQmbH",
    user: "Bob",
    description: "DIY eurorack at its finest",
    created_at: "2024-01-11T21:13:04.757Z",
    hashtags: [
      "#synth",
      "#musicproduction",
      "#handmade",
      "#modularsynthesizer",
      "#synthesizer",
    ],
  },
  {
    slug: "zb60-zudo-bus",
    imageAlt: "",
    blurhash: "UCD0J#_4%M~q~qRjRjRj%Mt7xuRj-;Rjxut7",
    user: "Takazudo",
    description: "Been working on this for months",
    created_at: "2025-02-25T14:43:50.303Z",
    hashtags: [
      "#analogsynth",
      "#modularsynthesizer",
      "#synth",
      "#DIYaudio",
      "#maker",
    ],
  },
  {
    slug: "zudo-block-build",
    imageAlt: "",
    blurhash: "UNDSCL~q-;xuD%%Mt7RjxuRjofWBRjWBRjWB",
    user: "Bob",
    description: "My modular case is finally complete",
    created_at: "2025-04-12T20:36:37.599Z",
    hashtags: [
      "#synth",
      "#woodworking",
      "#modularsynth",
      "#eurorack",
      "#synthesizer",
      "#musicproduction",
      "#eurorack",
      "#synthlife",
      "#studioporn",
    ],
  },
  {
    slug: "zudo-rail-connect1",
    imageAlt: "",
    blurhash: "U9ECnv00~q.8_N~q9FxuD%xuWBIU~qofM{M{",
    user: "Bob",
    description: "Perfect fit for my modules",
    created_at: "2025-03-29T21:35:48.522Z",
    hashtags: [
      "#studioporn",
      "#synth",
      "#studiosetup",
      "#woodworking",
      "#DIYproject",
      "#homestudio",
    ],
  },
  {
    slug: "zudo-rail-connect3",
    imageAlt: "",
    blurhash: "UCDcT{%M~q%MD%RjRjM{M{M{xuM{~qWBRjRj",
    user: "Takazudo",
    description: "Ready to make some noise",
    created_at: "2024-08-12T01:59:11.717Z",
    hashtags: [
      "#DIY",
      "#eurorack",
      "#handmade",
      "#musicproduction",
      "#DIYproject",
    ],
  },
  {
    slug: "zudo-rail-connect4",
    imageAlt: "",
    blurhash: "UBDcT{xu~q9F~qRjRjM{M{RjxuM{~qWBRjRj",
    user: "Takazudo",
    description: "Built this beauty over the weekend",
    created_at: "2024-08-14T21:02:43.726Z",
    hashtags: [
      "#woodworking",
      "#DIYaudio",
      "#synthlife",
      "#DIY",
      "#studioporn",
      "#modular",
      "#DIYcase",
    ],
  },
  {
    slug: "panels-gallery-zudo-blocks-101",
    imageAlt: "",
    blurhash: "UfK8O=s.s.S4M~WWs.R+}pazWCj?WDfQj@ay",
    user: "Takazudo",
    description: "So happy with this build",
    created_at: "2024-09-18T05:37:53.133Z",
    hashtags: ["#modularsynth", "#eurorack", "#eurorack"],
  },
  {
    slug: "panels-gallery-zudo-blocks-102",
    imageAlt: "",
    blurhash: "UhJE|nSgs.sCRlWXoeWV}psoWWj@R-WpoJjZ",
    user: "Alice",
    description: "My modular case is finally complete",
    created_at: "2024-04-26T21:32:34.483Z",
    hashtags: [
      "#studioporn",
      "#rackcase",
      "#musicgear",
      "#DIYaudio",
      "#DIYproject",
      "#patchcables",
      "#gearpost",
    ],
  },
];

/**
 * Get thumbnail URL for a given slug
 */
export function getThumbnailUrl(slug) {
  return `https://takazudomodular.com/static/images/p/${slug}/600w.webp`;
}

/**
 * Get enlarged image URL for a given slug
 */
export function getEnlargedImageUrl(slug) {
  return `https://takazudomodular.com/static/images/p/${slug}/1600w.webp`;
}

/**
 * Find a gallery item by its slug
 */
export function getGalleryItemBySlug(slug) {
  return galleryData.find((item) => item.slug === slug);
}
